//   Copyright (C) 2018 TASChain
//
//   This program is free software: you can redistribute it and/or modify
//   it under the terms of the GNU General Public License as published by
//   the Free Software Foundation, either version 3 of the License, or
//   (at your option) any later version.
//
//   This program is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//   GNU General Public License for more details.
//
//   You should have received a copy of the GNU General Public License
//   along with this program.  If not, see <https://www.gnu.org/licenses/>.

package groupsig

// POP is the signature of the private key to the public key
type Pop Signature

// GeneratePop is used to generate POP, which is a private key
// to public key serialized value signature.
func GeneratePop(sec Seckey, pub Pubkey) Pop {
	return Pop(Sign(sec, pub.Serialize()))
}

// VerifyPop is used to verify POP, public key is used to verify
// that POP is generated by the private key corresponding to the public key.
func VerifyPop(pub Pubkey, pop Pop) bool {
	return VerifySig(pub, pub.Serialize(), Signature(pop))
}
