// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tas.proto

/*
Package tas_pb is a generated protocol buffer package.

It is generated from these files:
	tas.proto

It has these top-level messages:
	Message
	Transaction
	TransactionRequestMessage
	TransactionSlice
	BlockHeader
	Block
	BlockSlice
	Member
	Group
	GroupSlice
	EntityRequestMessage
	Hashes
	Ratios
	BlockMessage
	GroupMessage
	SignData
	ConsensusGroupInitSummary
	PubKeyInfo
	ConsensusGroupRawMessage
	SharePiece
	ConsensusSharePieceMessage
	ConsensusSignPubKeyMessage
	StaticGroupInfo
	ConsensusGroupInitedMessage
	ConsensusCurrentMessage
	ConsensusBlockMessageBase
	ConsensusBlockMessage
*/
package tas_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Code             *uint32 `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	Signature        []byte  `protobuf:"bytes,2,opt,name=Signature" json:"Signature,omitempty"`
	Body             []byte  `protobuf:"bytes,3,opt,name=Body" json:"Body,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Message) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Transaction struct {
	Data             []byte  `protobuf:"bytes,1,req,name=Data" json:"Data,omitempty"`
	Value            *uint64 `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	Nonce            *uint64 `protobuf:"varint,3,req,name=Nonce" json:"Nonce,omitempty"`
	Source           []byte  `protobuf:"bytes,4,req,name=Source" json:"Source,omitempty"`
	Target           []byte  `protobuf:"bytes,5,opt,name=Target" json:"Target,omitempty"`
	GasLimit         *uint64 `protobuf:"varint,6,req,name=GasLimit" json:"GasLimit,omitempty"`
	GasPrice         *uint64 `protobuf:"varint,7,req,name=GasPrice" json:"GasPrice,omitempty"`
	Hash             []byte  `protobuf:"bytes,8,req,name=Hash" json:"Hash,omitempty"`
	ExtraData        []byte  `protobuf:"bytes,9,opt,name=ExtraData" json:"ExtraData,omitempty"`
	ExtraDataType    *int32  `protobuf:"varint,10,opt,name=ExtraDataType" json:"ExtraDataType,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Transaction) Reset()                    { *m = Transaction{} }
func (m *Transaction) String() string            { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()               {}
func (*Transaction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetValue() uint64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func (m *Transaction) GetSource() []byte {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Transaction) GetTarget() []byte {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Transaction) GetGasLimit() uint64 {
	if m != nil && m.GasLimit != nil {
		return *m.GasLimit
	}
	return 0
}

func (m *Transaction) GetGasPrice() uint64 {
	if m != nil && m.GasPrice != nil {
		return *m.GasPrice
	}
	return 0
}

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *Transaction) GetExtraDataType() int32 {
	if m != nil && m.ExtraDataType != nil {
		return *m.ExtraDataType
	}
	return 0
}

type TransactionRequestMessage struct {
	TransactionHashes [][]byte `protobuf:"bytes,1,rep,name=TransactionHashes" json:"TransactionHashes,omitempty"`
	SourceId          []byte   `protobuf:"bytes,2,req,name=SourceId" json:"SourceId,omitempty"`
	RequestTime       []byte   `protobuf:"bytes,3,req,name=RequestTime" json:"RequestTime,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *TransactionRequestMessage) Reset()                    { *m = TransactionRequestMessage{} }
func (m *TransactionRequestMessage) String() string            { return proto.CompactTextString(m) }
func (*TransactionRequestMessage) ProtoMessage()               {}
func (*TransactionRequestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TransactionRequestMessage) GetTransactionHashes() [][]byte {
	if m != nil {
		return m.TransactionHashes
	}
	return nil
}

func (m *TransactionRequestMessage) GetSourceId() []byte {
	if m != nil {
		return m.SourceId
	}
	return nil
}

func (m *TransactionRequestMessage) GetRequestTime() []byte {
	if m != nil {
		return m.RequestTime
	}
	return nil
}

type TransactionSlice struct {
	Transactions     []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *TransactionSlice) Reset()                    { *m = TransactionSlice{} }
func (m *TransactionSlice) String() string            { return proto.CompactTextString(m) }
func (*TransactionSlice) ProtoMessage()               {}
func (*TransactionSlice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TransactionSlice) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockHeader struct {
	Hash             []byte   `protobuf:"bytes,1,req,name=Hash" json:"Hash,omitempty"`
	Height           *uint64  `protobuf:"varint,2,req,name=Height" json:"Height,omitempty"`
	PreHash          []byte   `protobuf:"bytes,3,req,name=PreHash" json:"PreHash,omitempty"`
	PreTime          []byte   `protobuf:"bytes,4,req,name=PreTime" json:"PreTime,omitempty"`
	QueueNumber      *uint64  `protobuf:"varint,5,req,name=QueueNumber" json:"QueueNumber,omitempty"`
	CurTime          []byte   `protobuf:"bytes,6,req,name=CurTime" json:"CurTime,omitempty"`
	Castor           []byte   `protobuf:"bytes,7,req,name=Castor" json:"Castor,omitempty"`
	GroupId          []byte   `protobuf:"bytes,8,req,name=GroupId" json:"GroupId,omitempty"`
	Signature        []byte   `protobuf:"bytes,9,req,name=Signature" json:"Signature,omitempty"`
	Nonce            *uint64  `protobuf:"varint,10,req,name=Nonce" json:"Nonce,omitempty"`
	Transactions     [][]byte `protobuf:"bytes,11,rep,name=transactions" json:"transactions,omitempty"`
	TxTree           []byte   `protobuf:"bytes,12,req,name=TxTree" json:"TxTree,omitempty"`
	ReceiptTree      []byte   `protobuf:"bytes,13,req,name=ReceiptTree" json:"ReceiptTree,omitempty"`
	StateTree        []byte   `protobuf:"bytes,14,req,name=StateTree" json:"StateTree,omitempty"`
	ExtraData        []byte   `protobuf:"bytes,15,req,name=ExtraData" json:"ExtraData,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BlockHeader) Reset()                    { *m = BlockHeader{} }
func (m *BlockHeader) String() string            { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()               {}
func (*BlockHeader) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *BlockHeader) GetPreHash() []byte {
	if m != nil {
		return m.PreHash
	}
	return nil
}

func (m *BlockHeader) GetPreTime() []byte {
	if m != nil {
		return m.PreTime
	}
	return nil
}

func (m *BlockHeader) GetQueueNumber() uint64 {
	if m != nil && m.QueueNumber != nil {
		return *m.QueueNumber
	}
	return 0
}

func (m *BlockHeader) GetCurTime() []byte {
	if m != nil {
		return m.CurTime
	}
	return nil
}

func (m *BlockHeader) GetCastor() []byte {
	if m != nil {
		return m.Castor
	}
	return nil
}

func (m *BlockHeader) GetGroupId() []byte {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *BlockHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *BlockHeader) GetNonce() uint64 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *BlockHeader) GetTxTree() []byte {
	if m != nil {
		return m.TxTree
	}
	return nil
}

func (m *BlockHeader) GetReceiptTree() []byte {
	if m != nil {
		return m.ReceiptTree
	}
	return nil
}

func (m *BlockHeader) GetStateTree() []byte {
	if m != nil {
		return m.StateTree
	}
	return nil
}

func (m *BlockHeader) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

type Block struct {
	Header           *BlockHeader   `protobuf:"bytes,1,req,name=Header" json:"Header,omitempty"`
	Transactions     []*Transaction `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockSlice struct {
	Blocks           []*Block `protobuf:"bytes,1,rep,name=Blocks" json:"Blocks,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *BlockSlice) Reset()                    { *m = BlockSlice{} }
func (m *BlockSlice) String() string            { return proto.CompactTextString(m) }
func (*BlockSlice) ProtoMessage()               {}
func (*BlockSlice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *BlockSlice) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type Member struct {
	Id               []byte `protobuf:"bytes,1,req,name=Id" json:"Id,omitempty"`
	PubKey           []byte `protobuf:"bytes,2,req,name=PubKey" json:"PubKey,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Member) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Member) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type Group struct {
	Id               []byte    `protobuf:"bytes,1,req,name=Id" json:"Id,omitempty"`
	Members          []*Member `protobuf:"bytes,2,rep,name=Members" json:"Members,omitempty"`
	PubKey           []byte    `protobuf:"bytes,3,req,name=PubKey" json:"PubKey,omitempty"`
	Parent           []byte    `protobuf:"bytes,4,req,name=Parent" json:"Parent,omitempty"`
	Dummy            []byte    `protobuf:"bytes,5,req,name=Dummy" json:"Dummy,omitempty"`
	Signature        []byte    `protobuf:"bytes,6,req,name=Signature" json:"Signature,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Group) Reset()                    { *m = Group{} }
func (m *Group) String() string            { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()               {}
func (*Group) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Group) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Group) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Group) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Group) GetParent() []byte {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Group) GetDummy() []byte {
	if m != nil {
		return m.Dummy
	}
	return nil
}

func (m *Group) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type GroupSlice struct {
	Groups           []*Group `protobuf:"bytes,1,rep,name=Groups" json:"Groups,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *GroupSlice) Reset()                    { *m = GroupSlice{} }
func (m *GroupSlice) String() string            { return proto.CompactTextString(m) }
func (*GroupSlice) ProtoMessage()               {}
func (*GroupSlice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GroupSlice) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type EntityRequestMessage struct {
	SourceHeight      *uint64 `protobuf:"varint,1,req,name=SourceHeight" json:"SourceHeight,omitempty"`
	SourceCurrentHash []byte  `protobuf:"bytes,2,req,name=SourceCurrentHash" json:"SourceCurrentHash,omitempty"`
	SourceId          []byte  `protobuf:"bytes,3,req,name=SourceId" json:"SourceId,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *EntityRequestMessage) Reset()                    { *m = EntityRequestMessage{} }
func (m *EntityRequestMessage) String() string            { return proto.CompactTextString(m) }
func (*EntityRequestMessage) ProtoMessage()               {}
func (*EntityRequestMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *EntityRequestMessage) GetSourceHeight() uint64 {
	if m != nil && m.SourceHeight != nil {
		return *m.SourceHeight
	}
	return 0
}

func (m *EntityRequestMessage) GetSourceCurrentHash() []byte {
	if m != nil {
		return m.SourceCurrentHash
	}
	return nil
}

func (m *EntityRequestMessage) GetSourceId() []byte {
	if m != nil {
		return m.SourceId
	}
	return nil
}

type Hashes struct {
	Hashes           [][]byte `protobuf:"bytes,1,rep,name=hashes" json:"hashes,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Hashes) Reset()                    { *m = Hashes{} }
func (m *Hashes) String() string            { return proto.CompactTextString(m) }
func (*Hashes) ProtoMessage()               {}
func (*Hashes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Hashes) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type Ratios struct {
	Ratios           []float32 `protobuf:"fixed32,1,rep,name=ratios" json:"ratios,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Ratios) Reset()                    { *m = Ratios{} }
func (m *Ratios) String() string            { return proto.CompactTextString(m) }
func (*Ratios) ProtoMessage()               {}
func (*Ratios) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Ratios) GetRatios() []float32 {
	if m != nil {
		return m.Ratios
	}
	return nil
}

type BlockMessage struct {
	Blocks           *BlockSlice `protobuf:"bytes,1,opt,name=Blocks" json:"Blocks,omitempty"`
	Height           *uint64     `protobuf:"varint,2,opt,name=Height" json:"Height,omitempty"`
	Hashes           *Hashes     `protobuf:"bytes,3,opt,name=Hashes" json:"Hashes,omitempty"`
	Ratios           *Ratios     `protobuf:"bytes,4,opt,name=Ratios" json:"Ratios,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *BlockMessage) Reset()                    { *m = BlockMessage{} }
func (m *BlockMessage) String() string            { return proto.CompactTextString(m) }
func (*BlockMessage) ProtoMessage()               {}
func (*BlockMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *BlockMessage) GetBlocks() *BlockSlice {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *BlockMessage) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *BlockMessage) GetHashes() *Hashes {
	if m != nil {
		return m.Hashes
	}
	return nil
}

func (m *BlockMessage) GetRatios() *Ratios {
	if m != nil {
		return m.Ratios
	}
	return nil
}

type GroupMessage struct {
	Groups           *GroupSlice `protobuf:"bytes,1,opt,name=Groups" json:"Groups,omitempty"`
	Height           *uint64     `protobuf:"varint,2,opt,name=Height" json:"Height,omitempty"`
	Hash             []byte      `protobuf:"bytes,3,opt,name=Hash" json:"Hash,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GroupMessage) Reset()                    { *m = GroupMessage{} }
func (m *GroupMessage) String() string            { return proto.CompactTextString(m) }
func (*GroupMessage) ProtoMessage()               {}
func (*GroupMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GroupMessage) GetGroups() *GroupSlice {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *GroupMessage) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *GroupMessage) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type SignData struct {
	DataHash         []byte `protobuf:"bytes,1,req,name=DataHash" json:"DataHash,omitempty"`
	DataSign         []byte `protobuf:"bytes,2,req,name=DataSign" json:"DataSign,omitempty"`
	SignMember       []byte `protobuf:"bytes,3,req,name=SignMember" json:"SignMember,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SignData) Reset()                    { *m = SignData{} }
func (m *SignData) String() string            { return proto.CompactTextString(m) }
func (*SignData) ProtoMessage()               {}
func (*SignData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SignData) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *SignData) GetDataSign() []byte {
	if m != nil {
		return m.DataSign
	}
	return nil
}

func (m *SignData) GetSignMember() []byte {
	if m != nil {
		return m.SignMember
	}
	return nil
}

type ConsensusGroupInitSummary struct {
	ParentID         []byte  `protobuf:"bytes,1,req,name=ParentID" json:"ParentID,omitempty"`
	Authority        *uint64 `protobuf:"varint,2,req,name=Authority" json:"Authority,omitempty"`
	Name             []byte  `protobuf:"bytes,3,req,name=Name" json:"Name,omitempty"`
	DummyID          []byte  `protobuf:"bytes,4,req,name=DummyID" json:"DummyID,omitempty"`
	BeginTime        []byte  `protobuf:"bytes,5,req,name=BeginTime" json:"BeginTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ConsensusGroupInitSummary) Reset()                    { *m = ConsensusGroupInitSummary{} }
func (m *ConsensusGroupInitSummary) String() string            { return proto.CompactTextString(m) }
func (*ConsensusGroupInitSummary) ProtoMessage()               {}
func (*ConsensusGroupInitSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *ConsensusGroupInitSummary) GetParentID() []byte {
	if m != nil {
		return m.ParentID
	}
	return nil
}

func (m *ConsensusGroupInitSummary) GetAuthority() uint64 {
	if m != nil && m.Authority != nil {
		return *m.Authority
	}
	return 0
}

func (m *ConsensusGroupInitSummary) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ConsensusGroupInitSummary) GetDummyID() []byte {
	if m != nil {
		return m.DummyID
	}
	return nil
}

func (m *ConsensusGroupInitSummary) GetBeginTime() []byte {
	if m != nil {
		return m.BeginTime
	}
	return nil
}

type PubKeyInfo struct {
	ID               []byte `protobuf:"bytes,1,req,name=ID" json:"ID,omitempty"`
	PublicKey        []byte `protobuf:"bytes,2,req,name=PublicKey" json:"PublicKey,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PubKeyInfo) Reset()                    { *m = PubKeyInfo{} }
func (m *PubKeyInfo) String() string            { return proto.CompactTextString(m) }
func (*PubKeyInfo) ProtoMessage()               {}
func (*PubKeyInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *PubKeyInfo) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *PubKeyInfo) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type ConsensusGroupRawMessage struct {
	ConsensusGroupInitSummary *ConsensusGroupInitSummary `protobuf:"bytes,1,req,name=ConsensusGroupInitSummary" json:"ConsensusGroupInitSummary,omitempty"`
	Ids                       []*PubKeyInfo              `protobuf:"bytes,2,rep,name=Ids" json:"Ids,omitempty"`
	Sign                      *SignData                  `protobuf:"bytes,3,req,name=sign" json:"sign,omitempty"`
	XXX_unrecognized          []byte                     `json:"-"`
}

func (m *ConsensusGroupRawMessage) Reset()                    { *m = ConsensusGroupRawMessage{} }
func (m *ConsensusGroupRawMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusGroupRawMessage) ProtoMessage()               {}
func (*ConsensusGroupRawMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ConsensusGroupRawMessage) GetConsensusGroupInitSummary() *ConsensusGroupInitSummary {
	if m != nil {
		return m.ConsensusGroupInitSummary
	}
	return nil
}

func (m *ConsensusGroupRawMessage) GetIds() []*PubKeyInfo {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ConsensusGroupRawMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type SharePiece struct {
	Seckey           []byte `protobuf:"bytes,1,req,name=Seckey" json:"Seckey,omitempty"`
	Pubkey           []byte `protobuf:"bytes,2,req,name=Pubkey" json:"Pubkey,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SharePiece) Reset()                    { *m = SharePiece{} }
func (m *SharePiece) String() string            { return proto.CompactTextString(m) }
func (*SharePiece) ProtoMessage()               {}
func (*SharePiece) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *SharePiece) GetSeckey() []byte {
	if m != nil {
		return m.Seckey
	}
	return nil
}

func (m *SharePiece) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

type ConsensusSharePieceMessage struct {
	GISHash          []byte      `protobuf:"bytes,1,req,name=GISHash" json:"GISHash,omitempty"`
	DummyID          []byte      `protobuf:"bytes,2,req,name=DummyID" json:"DummyID,omitempty"`
	Dest             []byte      `protobuf:"bytes,3,req,name=Dest" json:"Dest,omitempty"`
	SharePiece       *SharePiece `protobuf:"bytes,4,req,name=SharePiece" json:"SharePiece,omitempty"`
	Sign             *SignData   `protobuf:"bytes,5,req,name=Sign" json:"Sign,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ConsensusSharePieceMessage) Reset()                    { *m = ConsensusSharePieceMessage{} }
func (m *ConsensusSharePieceMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusSharePieceMessage) ProtoMessage()               {}
func (*ConsensusSharePieceMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *ConsensusSharePieceMessage) GetGISHash() []byte {
	if m != nil {
		return m.GISHash
	}
	return nil
}

func (m *ConsensusSharePieceMessage) GetDummyID() []byte {
	if m != nil {
		return m.DummyID
	}
	return nil
}

func (m *ConsensusSharePieceMessage) GetDest() []byte {
	if m != nil {
		return m.Dest
	}
	return nil
}

func (m *ConsensusSharePieceMessage) GetSharePiece() *SharePiece {
	if m != nil {
		return m.SharePiece
	}
	return nil
}

func (m *ConsensusSharePieceMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ConsensusSignPubKeyMessage struct {
	GISHash          []byte    `protobuf:"bytes,1,req,name=GISHash" json:"GISHash,omitempty"`
	DummyID          []byte    `protobuf:"bytes,2,req,name=DummyID" json:"DummyID,omitempty"`
	SignPK           []byte    `protobuf:"bytes,3,req,name=SignPK" json:"SignPK,omitempty"`
	SignData         *SignData `protobuf:"bytes,4,req,name=SignData" json:"SignData,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ConsensusSignPubKeyMessage) Reset()                    { *m = ConsensusSignPubKeyMessage{} }
func (m *ConsensusSignPubKeyMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusSignPubKeyMessage) ProtoMessage()               {}
func (*ConsensusSignPubKeyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *ConsensusSignPubKeyMessage) GetGISHash() []byte {
	if m != nil {
		return m.GISHash
	}
	return nil
}

func (m *ConsensusSignPubKeyMessage) GetDummyID() []byte {
	if m != nil {
		return m.DummyID
	}
	return nil
}

func (m *ConsensusSignPubKeyMessage) GetSignPK() []byte {
	if m != nil {
		return m.SignPK
	}
	return nil
}

func (m *ConsensusSignPubKeyMessage) GetSignData() *SignData {
	if m != nil {
		return m.SignData
	}
	return nil
}

type StaticGroupInfo struct {
	GroupID          []byte                     `protobuf:"bytes,1,req,name=GroupID" json:"GroupID,omitempty"`
	GroupPK          []byte                     `protobuf:"bytes,2,req,name=GroupPK" json:"GroupPK,omitempty"`
	Members          []*PubKeyInfo              `protobuf:"bytes,3,rep,name=members" json:"members,omitempty"`
	Gis              *ConsensusGroupInitSummary `protobuf:"bytes,4,req,name=Gis" json:"Gis,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *StaticGroupInfo) Reset()                    { *m = StaticGroupInfo{} }
func (m *StaticGroupInfo) String() string            { return proto.CompactTextString(m) }
func (*StaticGroupInfo) ProtoMessage()               {}
func (*StaticGroupInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *StaticGroupInfo) GetGroupID() []byte {
	if m != nil {
		return m.GroupID
	}
	return nil
}

func (m *StaticGroupInfo) GetGroupPK() []byte {
	if m != nil {
		return m.GroupPK
	}
	return nil
}

func (m *StaticGroupInfo) GetMembers() []*PubKeyInfo {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *StaticGroupInfo) GetGis() *ConsensusGroupInitSummary {
	if m != nil {
		return m.Gis
	}
	return nil
}

type ConsensusGroupInitedMessage struct {
	StaticGroupInfo  *StaticGroupInfo `protobuf:"bytes,1,req,name=StaticGroupInfo" json:"StaticGroupInfo,omitempty"`
	Sign             *SignData        `protobuf:"bytes,2,req,name=Sign" json:"Sign,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ConsensusGroupInitedMessage) Reset()                    { *m = ConsensusGroupInitedMessage{} }
func (m *ConsensusGroupInitedMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusGroupInitedMessage) ProtoMessage()               {}
func (*ConsensusGroupInitedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *ConsensusGroupInitedMessage) GetStaticGroupInfo() *StaticGroupInfo {
	if m != nil {
		return m.StaticGroupInfo
	}
	return nil
}

func (m *ConsensusGroupInitedMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ConsensusCurrentMessage struct {
	GroupID          []byte    `protobuf:"bytes,1,req,name=GroupID" json:"GroupID,omitempty"`
	PreHash          []byte    `protobuf:"bytes,2,req,name=PreHash" json:"PreHash,omitempty"`
	PreTime          []byte    `protobuf:"bytes,3,req,name=PreTime" json:"PreTime,omitempty"`
	BlockHeight      *uint64   `protobuf:"varint,4,req,name=BlockHeight" json:"BlockHeight,omitempty"`
	Instigator       []byte    `protobuf:"bytes,5,req,name=Instigator" json:"Instigator,omitempty"`
	Sign             *SignData `protobuf:"bytes,6,req,name=Sign" json:"Sign,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ConsensusCurrentMessage) Reset()                    { *m = ConsensusCurrentMessage{} }
func (m *ConsensusCurrentMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusCurrentMessage) ProtoMessage()               {}
func (*ConsensusCurrentMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *ConsensusCurrentMessage) GetGroupID() []byte {
	if m != nil {
		return m.GroupID
	}
	return nil
}

func (m *ConsensusCurrentMessage) GetPreHash() []byte {
	if m != nil {
		return m.PreHash
	}
	return nil
}

func (m *ConsensusCurrentMessage) GetPreTime() []byte {
	if m != nil {
		return m.PreTime
	}
	return nil
}

func (m *ConsensusCurrentMessage) GetBlockHeight() uint64 {
	if m != nil && m.BlockHeight != nil {
		return *m.BlockHeight
	}
	return 0
}

func (m *ConsensusCurrentMessage) GetInstigator() []byte {
	if m != nil {
		return m.Instigator
	}
	return nil
}

func (m *ConsensusCurrentMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ConsensusBlockMessageBase struct {
	Bh               *BlockHeader `protobuf:"bytes,1,req,name=Bh" json:"Bh,omitempty"`
	GroupID          []byte       `protobuf:"bytes,2,req,name=GroupID" json:"GroupID,omitempty"`
	Sign             *SignData    `protobuf:"bytes,3,req,name=Sign" json:"Sign,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *ConsensusBlockMessageBase) Reset()                    { *m = ConsensusBlockMessageBase{} }
func (m *ConsensusBlockMessageBase) String() string            { return proto.CompactTextString(m) }
func (*ConsensusBlockMessageBase) ProtoMessage()               {}
func (*ConsensusBlockMessageBase) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *ConsensusBlockMessageBase) GetBh() *BlockHeader {
	if m != nil {
		return m.Bh
	}
	return nil
}

func (m *ConsensusBlockMessageBase) GetGroupID() []byte {
	if m != nil {
		return m.GroupID
	}
	return nil
}

func (m *ConsensusBlockMessageBase) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ConsensusBlockMessage struct {
	Block            *Block    `protobuf:"bytes,1,req,name=Block" json:"Block,omitempty"`
	GroupID          []byte    `protobuf:"bytes,2,req,name=GroupID" json:"GroupID,omitempty"`
	SignData         *SignData `protobuf:"bytes,3,req,name=SignData" json:"SignData,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *ConsensusBlockMessage) Reset()                    { *m = ConsensusBlockMessage{} }
func (m *ConsensusBlockMessage) String() string            { return proto.CompactTextString(m) }
func (*ConsensusBlockMessage) ProtoMessage()               {}
func (*ConsensusBlockMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ConsensusBlockMessage) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *ConsensusBlockMessage) GetGroupID() []byte {
	if m != nil {
		return m.GroupID
	}
	return nil
}

func (m *ConsensusBlockMessage) GetSignData() *SignData {
	if m != nil {
		return m.SignData
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "tas.pb.Message")
	proto.RegisterType((*Transaction)(nil), "tas.pb.Transaction")
	proto.RegisterType((*TransactionRequestMessage)(nil), "tas.pb.TransactionRequestMessage")
	proto.RegisterType((*TransactionSlice)(nil), "tas.pb.TransactionSlice")
	proto.RegisterType((*BlockHeader)(nil), "tas.pb.BlockHeader")
	proto.RegisterType((*Block)(nil), "tas.pb.Block")
	proto.RegisterType((*BlockSlice)(nil), "tas.pb.BlockSlice")
	proto.RegisterType((*Member)(nil), "tas.pb.Member")
	proto.RegisterType((*Group)(nil), "tas.pb.Group")
	proto.RegisterType((*GroupSlice)(nil), "tas.pb.GroupSlice")
	proto.RegisterType((*EntityRequestMessage)(nil), "tas.pb.EntityRequestMessage")
	proto.RegisterType((*Hashes)(nil), "tas.pb.Hashes")
	proto.RegisterType((*Ratios)(nil), "tas.pb.Ratios")
	proto.RegisterType((*BlockMessage)(nil), "tas.pb.BlockMessage")
	proto.RegisterType((*GroupMessage)(nil), "tas.pb.GroupMessage")
	proto.RegisterType((*SignData)(nil), "tas.pb.SignData")
	proto.RegisterType((*ConsensusGroupInitSummary)(nil), "tas.pb.ConsensusGroupInitSummary")
	proto.RegisterType((*PubKeyInfo)(nil), "tas.pb.PubKeyInfo")
	proto.RegisterType((*ConsensusGroupRawMessage)(nil), "tas.pb.ConsensusGroupRawMessage")
	proto.RegisterType((*SharePiece)(nil), "tas.pb.SharePiece")
	proto.RegisterType((*ConsensusSharePieceMessage)(nil), "tas.pb.ConsensusSharePieceMessage")
	proto.RegisterType((*ConsensusSignPubKeyMessage)(nil), "tas.pb.ConsensusSignPubKeyMessage")
	proto.RegisterType((*StaticGroupInfo)(nil), "tas.pb.StaticGroupInfo")
	proto.RegisterType((*ConsensusGroupInitedMessage)(nil), "tas.pb.ConsensusGroupInitedMessage")
	proto.RegisterType((*ConsensusCurrentMessage)(nil), "tas.pb.ConsensusCurrentMessage")
	proto.RegisterType((*ConsensusBlockMessageBase)(nil), "tas.pb.ConsensusBlockMessageBase")
	proto.RegisterType((*ConsensusBlockMessage)(nil), "tas.pb.ConsensusBlockMessage")
}

func init() { proto.RegisterFile("tas.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xd6, 0xee, 0xda, 0x4e, 0xf2, 0xec, 0xb4, 0x65, 0x29, 0xed, 0xb6, 0x20, 0x64, 0xb6, 0xa1,
	0xb2, 0x20, 0x8a, 0x50, 0x7a, 0x40, 0x42, 0x5c, 0xea, 0xb8, 0x4a, 0xac, 0xd0, 0x60, 0xc6, 0x11,
	0x57, 0x34, 0xb1, 0x27, 0xf6, 0x2a, 0xf1, 0x6e, 0xd8, 0x9d, 0x15, 0xf5, 0x8d, 0x43, 0x05, 0x27,
	0xae, 0xdc, 0x41, 0x42, 0x82, 0x7f, 0x82, 0x2b, 0x47, 0xfe, 0x25, 0xf4, 0xde, 0xfc, 0xd8, 0xd9,
	0x18, 0x9b, 0x4a, 0x9c, 0x76, 0xbe, 0xf7, 0x66, 0x67, 0xbe, 0xf7, 0xbe, 0x37, 0x6f, 0x06, 0x76,
	0x24, 0x2f, 0x0e, 0x6e, 0xf2, 0x4c, 0x66, 0x61, 0x8b, 0x86, 0x17, 0xf1, 0x97, 0xb0, 0xf5, 0x52,
	0x14, 0x05, 0x9f, 0x89, 0x30, 0x84, 0xc6, 0x51, 0x36, 0x15, 0x91, 0xd7, 0xf5, 0x7b, 0xbb, 0x8c,
	0xc6, 0xe1, 0x7b, 0xb0, 0x33, 0x4e, 0x66, 0x29, 0x97, 0x65, 0x2e, 0x22, 0xbf, 0xeb, 0xf5, 0x3a,
	0xac, 0x32, 0xe0, 0x1f, 0xfd, 0x6c, 0xba, 0x8c, 0x02, 0x72, 0xd0, 0x38, 0xfe, 0xc9, 0x87, 0xf6,
	0x79, 0xce, 0xd3, 0x82, 0x4f, 0x64, 0x92, 0xa5, 0x38, 0x67, 0xc0, 0x25, 0xa7, 0x55, 0x3b, 0x8c,
	0xc6, 0xe1, 0x7d, 0x68, 0x7e, 0xcd, 0xaf, 0x4b, 0xb5, 0x62, 0x83, 0x29, 0x80, 0xd6, 0xb3, 0x2c,
	0x9d, 0x88, 0x28, 0xe8, 0xfa, 0x68, 0x25, 0x10, 0x3e, 0x80, 0xd6, 0x38, 0x2b, 0xf3, 0x89, 0x88,
	0x1a, 0xb4, 0x82, 0x46, 0x68, 0x3f, 0xe7, 0xf9, 0x4c, 0xc8, 0xa8, 0x49, 0xbb, 0x6b, 0x14, 0x3e,
	0x86, 0xed, 0x63, 0x5e, 0x7c, 0x91, 0x2c, 0x12, 0x19, 0xb5, 0x68, 0x21, 0x8b, 0xb5, 0x6f, 0x94,
	0x27, 0x13, 0x11, 0x6d, 0x59, 0x1f, 0x61, 0xe4, 0x79, 0xc2, 0x8b, 0x79, 0xb4, 0xad, 0x78, 0xe2,
	0x18, 0xa3, 0x7f, 0xf1, 0x4a, 0xe6, 0x9c, 0x02, 0xd8, 0x51, 0xd1, 0x5b, 0x43, 0xb8, 0x07, 0xbb,
	0x16, 0x9c, 0x2f, 0x6f, 0x44, 0x04, 0x5d, 0xaf, 0xd7, 0x64, 0x75, 0x63, 0xfc, 0xa3, 0x07, 0x8f,
	0x9c, 0x7c, 0x30, 0xf1, 0x6d, 0x29, 0x0a, 0x69, 0x72, 0xbe, 0x0f, 0x6f, 0x39, 0x4e, 0xdc, 0x54,
	0x14, 0x91, 0xd7, 0x0d, 0x7a, 0x1d, 0xb6, 0xea, 0x40, 0xfe, 0x2a, 0xfa, 0xe1, 0x34, 0xf2, 0x89,
	0xa7, 0xc5, 0x61, 0x17, 0xda, 0x7a, 0xed, 0xf3, 0x64, 0xa1, 0x72, 0xd8, 0x61, 0xae, 0x29, 0x3e,
	0x85, 0x7b, 0xce, 0x92, 0xe3, 0x6b, 0x8c, 0xfa, 0x53, 0xe8, 0xc8, 0xca, 0xa6, 0xb6, 0x6e, 0x1f,
	0xbe, 0x7d, 0xa0, 0xaa, 0xe3, 0xc0, 0x25, 0x5e, 0x9b, 0x18, 0xff, 0x11, 0x40, 0xbb, 0x7f, 0x9d,
	0x4d, 0xae, 0x4e, 0x04, 0x9f, 0x8a, 0xdc, 0xa6, 0xcf, 0x73, 0xd2, 0xf7, 0x00, 0x5a, 0x27, 0x22,
	0x99, 0xcd, 0x25, 0x91, 0x6d, 0x30, 0x8d, 0xc2, 0x08, 0xb6, 0x46, 0xb9, 0xa0, 0xe9, 0x8a, 0xa6,
	0x81, 0xda, 0x43, 0x01, 0x34, 0xac, 0x07, 0x21, 0x86, 0xf7, 0x55, 0x29, 0x4a, 0x71, 0x56, 0x2e,
	0x2e, 0x44, 0x1e, 0x35, 0x69, 0x41, 0xd7, 0x84, 0xff, 0x1e, 0x95, 0x39, 0xfd, 0xdb, 0x52, 0xff,
	0x6a, 0x88, 0x3c, 0x8e, 0x78, 0x21, 0xb3, 0x9c, 0x44, 0xef, 0x30, 0x8d, 0xf0, 0x8f, 0xe3, 0x3c,
	0x2b, 0x6f, 0x86, 0x53, 0xad, 0xba, 0x81, 0xf5, 0xb2, 0xdf, 0x21, 0x9f, 0x53, 0xf6, 0xb6, 0x50,
	0xc1, 0x2d, 0xd4, 0xf8, 0x56, 0x2a, 0xdb, 0xa4, 0x62, 0xcd, 0x46, 0x45, 0xfb, 0xea, 0x3c, 0x17,
	0x22, 0xea, 0x28, 0x26, 0x0a, 0x29, 0xf1, 0x26, 0x22, 0xb9, 0x91, 0xe4, 0xdc, 0x35, 0xe2, 0x59,
	0x13, 0x31, 0x92, 0x5c, 0x0a, 0xf2, 0xdf, 0xd1, 0x8c, 0x8c, 0xa1, 0x5e, 0xa8, 0x77, 0x95, 0xd7,
	0x1a, 0xe2, 0x05, 0x34, 0x49, 0xaa, 0xf0, 0x63, 0x14, 0x04, 0xe5, 0x22, 0x99, 0x1c, 0x9d, 0x1d,
	0x25, 0x99, 0x9e, 0xb2, 0x52, 0x1a, 0xfe, 0x9b, 0x96, 0xc6, 0x33, 0x00, 0x5a, 0x4f, 0x55, 0xd8,
	0x87, 0xd0, 0x22, 0x64, 0x6a, 0x6b, 0xb7, 0xb6, 0x27, 0xd3, 0xce, 0xf8, 0x13, 0x68, 0xbd, 0x14,
	0xa4, 0xe3, 0x1d, 0xf0, 0x87, 0x53, 0x5d, 0x47, 0xfe, 0x70, 0x8a, 0x39, 0x1b, 0x95, 0x17, 0xa7,
	0x62, 0xa9, 0x4b, 0x5e, 0xa3, 0xf8, 0x37, 0x0f, 0x9a, 0xa4, 0xd7, 0xca, 0x1f, 0x3d, 0xec, 0x69,
	0xb8, 0x96, 0x21, 0x7d, 0xc7, 0xec, 0xa9, 0xcc, 0xcc, 0xb8, 0x9d, 0xb5, 0x03, 0x77, 0x6d, 0xb2,
	0xf3, 0x5c, 0xa4, 0xd2, 0x34, 0x1d, 0x85, 0x50, 0xf9, 0x41, 0xb9, 0x58, 0x2c, 0xa9, 0xfe, 0x3a,
	0x4c, 0x81, 0x7a, 0xb5, 0xb4, 0x6e, 0x55, 0x0b, 0xa6, 0x83, 0x68, 0xda, 0x74, 0x10, 0x5a, 0x49,
	0x07, 0x59, 0x99, 0x76, 0xc6, 0xaf, 0x3d, 0xb8, 0xff, 0x22, 0x95, 0x89, 0x5c, 0xde, 0x6a, 0x18,
	0x31, 0x74, 0xd4, 0x91, 0xd7, 0x27, 0xcb, 0xa3, 0x12, 0xac, 0xd9, 0xb0, 0xa9, 0x28, 0x7c, 0x54,
	0xe6, 0x48, 0x9b, 0x4e, 0x9a, 0x4a, 0xde, 0xaa, 0xa3, 0xd6, 0x54, 0x82, 0x7a, 0x53, 0x89, 0xbb,
	0xd0, 0xd2, 0xad, 0xe7, 0x01, 0xb4, 0xe6, 0x6e, 0x77, 0xd2, 0x08, 0x67, 0x30, 0x2e, 0x93, 0x8c,
	0x66, 0xe4, 0x34, 0xa2, 0x19, 0x3e, 0xd3, 0x28, 0xfe, 0xd5, 0x83, 0x0e, 0x89, 0x6c, 0x42, 0xf8,
	0xc8, 0xa9, 0x08, 0xaf, 0xd7, 0x3e, 0x0c, 0x6b, 0x15, 0x41, 0x69, 0x32, 0x65, 0x51, 0x6b, 0x21,
	0x9e, 0xd3, 0x42, 0x9e, 0x1a, 0x62, 0x74, 0xf7, 0x38, 0x0a, 0x2b, 0x2b, 0x33, 0xb4, 0x9f, 0x1a,
	0x7a, 0x51, 0xa3, 0x3e, 0x4f, 0x59, 0x99, 0xf6, 0xc6, 0x97, 0xd0, 0xa1, 0xcc, 0x3b, 0x1c, 0xad,
	0x4c, 0x35, 0x8e, 0x95, 0x94, 0x46, 0xab, 0xb5, 0x1c, 0x4d, 0x4b, 0xd4, 0xb7, 0x23, 0x8e, 0xe3,
	0x0b, 0xd8, 0xc6, 0xca, 0xa0, 0xfb, 0xe3, 0x31, 0x6c, 0xe3, 0xd7, 0x69, 0x9b, 0x16, 0x1b, 0x1f,
	0xce, 0x35, 0x9d, 0xde, 0xe0, 0xf0, 0x7d, 0x00, 0xfc, 0xaa, 0x1a, 0xd6, 0x92, 0x39, 0x96, 0xf8,
	0x17, 0x0f, 0x1e, 0x1d, 0x65, 0x69, 0x21, 0xd2, 0xa2, 0x2c, 0x54, 0x47, 0x4b, 0x13, 0x39, 0x2e,
	0x17, 0x0b, 0x9e, 0x2f, 0x71, 0x65, 0x55, 0xcc, 0xc3, 0x81, 0xd9, 0xd5, 0x60, 0x2c, 0xe4, 0xe7,
	0xa5, 0x9c, 0x67, 0x79, 0x22, 0x97, 0xba, 0x67, 0x57, 0x06, 0x8c, 0xe7, 0x8c, 0xdb, 0xab, 0x85,
	0xc6, 0xd8, 0x42, 0xe9, 0x0c, 0x0c, 0x07, 0xa6, 0x61, 0x6b, 0x88, 0x6b, 0xf5, 0xc5, 0x2c, 0x49,
	0xa9, 0x21, 0xab, 0xe3, 0x52, 0x19, 0xe2, 0xcf, 0x00, 0xd4, 0x51, 0x1b, 0xa6, 0x97, 0x19, 0x1d,
	0xe0, 0x81, 0x3d, 0xc0, 0xf4, 0xef, 0xa8, 0xbc, 0xb8, 0x4e, 0x26, 0xd5, 0xa9, 0xaf, 0x0c, 0xf1,
	0x5f, 0x1e, 0x44, 0xf5, 0xf8, 0x18, 0xff, 0xce, 0x08, 0xf7, 0xcd, 0x86, 0xd8, 0x75, 0xd7, 0xfb,
	0xc0, 0x68, 0xb9, 0x76, 0x22, 0xdb, 0x90, 0xbf, 0x3d, 0x08, 0x86, 0x53, 0xd3, 0x58, 0x6c, 0x59,
	0x54, 0xc1, 0x30, 0x74, 0x87, 0x7b, 0xd0, 0x28, 0x50, 0xbb, 0x80, 0x76, 0xbc, 0x67, 0xa6, 0x19,
	0xed, 0x19, 0x79, 0xe3, 0xcf, 0x01, 0xc6, 0x73, 0x9e, 0x8b, 0x51, 0x22, 0xf4, 0x4b, 0x47, 0x4c,
	0xae, 0xc4, 0x52, 0x67, 0x42, 0x23, 0xdd, 0xa4, 0xae, 0x6a, 0x0d, 0xf0, 0x4a, 0x2c, 0xe3, 0x3f,
	0x3d, 0x78, 0x6c, 0x79, 0x56, 0xeb, 0x98, 0x4c, 0xe0, 0xed, 0x36, 0x1c, 0x3b, 0xd5, 0x65, 0xa0,
	0x2b, 0x9a, 0x5f, 0x17, 0x0d, 0x1f, 0x6b, 0xa2, 0x90, 0x46, 0x62, 0x1c, 0x87, 0x87, 0x2e, 0x49,
	0x52, 0xd9, 0x89, 0xbb, 0xf2, 0x30, 0x37, 0x94, 0x3d, 0x68, 0x50, 0xe9, 0x36, 0xd7, 0x85, 0x8f,
	0xa3, 0xf8, 0xe7, 0x5a, 0x00, 0xc9, 0x2c, 0x55, 0x59, 0xfc, 0x3f, 0x01, 0x60, 0x0e, 0x71, 0xa1,
	0x53, 0xd3, 0xd0, 0x15, 0x0a, 0xf7, 0xab, 0x73, 0xa7, 0x43, 0x58, 0x25, 0x65, 0x67, 0xc4, 0xbf,
	0x7b, 0x70, 0x17, 0x2f, 0xd7, 0x64, 0xa2, 0xe5, 0xbf, 0xcc, 0xaa, 0xc7, 0xc2, 0xc0, 0xb2, 0x51,
	0xd0, 0x7a, 0x46, 0xa7, 0x86, 0x8d, 0x86, 0xe1, 0x3e, 0x6c, 0x2d, 0xf4, 0x45, 0x14, 0xac, 0xad,
	0x17, 0x33, 0x25, 0x7c, 0x06, 0xc1, 0x71, 0x52, 0x68, 0x7a, 0x6f, 0x50, 0xa4, 0x38, 0x3b, 0xfe,
	0xc1, 0x83, 0x77, 0x57, 0xa7, 0x88, 0xa9, 0x49, 0xe2, 0xf3, 0x95, 0x48, 0xf4, 0x29, 0x78, 0x68,
	0xe3, 0xaf, 0xbb, 0xd9, 0x4a, 0xe4, 0x46, 0x4c, 0x7f, 0xa3, 0x98, 0x7f, 0x7b, 0xf0, 0xd0, 0x12,
	0xd1, 0xf7, 0x8b, 0xab, 0xe4, 0xda, 0xdc, 0x99, 0xa7, 0xa0, 0xbf, 0xf6, 0x29, 0x18, 0xac, 0x3c,
	0x05, 0xf5, 0x7b, 0x85, 0x9a, 0x6e, 0x43, 0x3d, 0x05, 0x1d, 0x13, 0x76, 0xc8, 0x61, 0x5a, 0xc8,
	0x64, 0xc6, 0xf1, 0xd1, 0xa7, 0x9a, 0x8f, 0x63, 0xb1, 0x11, 0xb5, 0x36, 0x46, 0xf4, 0xbd, 0xdb,
	0x47, 0xdd, 0x1b, 0xac, 0xcf, 0x0b, 0x11, 0x3e, 0x01, 0xbf, 0x3f, 0xdf, 0xf4, 0x8e, 0xf2, 0xfb,
	0x73, 0x37, 0x70, 0xbf, 0x1e, 0xb8, 0xa1, 0x10, 0x6c, 0xa4, 0xf0, 0xda, 0x83, 0x77, 0xfe, 0x95,
	0x42, 0xf8, 0x44, 0xbf, 0xe9, 0x34, 0x83, 0x5b, 0xaf, 0x2a, 0xfd, 0xde, 0x5b, 0xbf, 0xbd, 0x7b,
	0x1e, 0x82, 0xff, 0x3a, 0x0f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x8f, 0xe5, 0x77, 0x15, 0x38,
	0x0e, 0x00, 0x00,
}
