// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tas.proto

package tas_middleware_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Code                 *uint32  `protobuf:"varint,1,req,name=Code" json:"Code,omitempty"`
	Signature            []byte   `protobuf:"bytes,2,opt,name=Signature" json:"Signature,omitempty"`
	Body                 []byte   `protobuf:"bytes,3,opt,name=Body" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetCode() uint32 {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return 0
}

func (m *Message) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Transaction struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
	Value                *uint64  `protobuf:"varint,2,opt,name=Value" json:"Value,omitempty"`
	Nonce                *uint64  `protobuf:"varint,3,req,name=Nonce" json:"Nonce,omitempty"`
	Source               []byte   `protobuf:"bytes,4,req,name=Source" json:"Source,omitempty"`
	Target               []byte   `protobuf:"bytes,5,opt,name=Target" json:"Target,omitempty"`
	GasLimit             *uint64  `protobuf:"varint,6,req,name=GasLimit" json:"GasLimit,omitempty"`
	GasPrice             *uint64  `protobuf:"varint,7,req,name=GasPrice" json:"GasPrice,omitempty"`
	Hash                 []byte   `protobuf:"bytes,8,req,name=Hash" json:"Hash,omitempty"`
	ExtraData            []byte   `protobuf:"bytes,9,opt,name=ExtraData" json:"ExtraData,omitempty"`
	ExtraDataType        *int32   `protobuf:"varint,10,opt,name=ExtraDataType" json:"ExtraDataType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{1}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetValue() uint64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

func (m *Transaction) GetNonce() uint64 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func (m *Transaction) GetSource() []byte {
	if m != nil {
		return m.Source
	}
	return nil
}

func (m *Transaction) GetTarget() []byte {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *Transaction) GetGasLimit() uint64 {
	if m != nil && m.GasLimit != nil {
		return *m.GasLimit
	}
	return 0
}

func (m *Transaction) GetGasPrice() uint64 {
	if m != nil && m.GasPrice != nil {
		return *m.GasPrice
	}
	return 0
}

func (m *Transaction) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Transaction) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *Transaction) GetExtraDataType() int32 {
	if m != nil && m.ExtraDataType != nil {
		return *m.ExtraDataType
	}
	return 0
}

type TransactionRequestMessage struct {
	TransactionHashes    [][]byte `protobuf:"bytes,1,rep,name=TransactionHashes" json:"TransactionHashes,omitempty"`
	CurrentBlockHash     []byte   `protobuf:"bytes,2,req,name=CurrentBlockHash" json:"CurrentBlockHash,omitempty"`
	BlockHeight          *uint64  `protobuf:"varint,3,req,name=BlockHeight" json:"BlockHeight,omitempty"`
	BlockQn              *uint64  `protobuf:"varint,4,req,name=BlockQn" json:"BlockQn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRequestMessage) Reset()         { *m = TransactionRequestMessage{} }
func (m *TransactionRequestMessage) String() string { return proto.CompactTextString(m) }
func (*TransactionRequestMessage) ProtoMessage()    {}
func (*TransactionRequestMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{2}
}
func (m *TransactionRequestMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequestMessage.Unmarshal(m, b)
}
func (m *TransactionRequestMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequestMessage.Marshal(b, m, deterministic)
}
func (dst *TransactionRequestMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequestMessage.Merge(dst, src)
}
func (m *TransactionRequestMessage) XXX_Size() int {
	return xxx_messageInfo_TransactionRequestMessage.Size(m)
}
func (m *TransactionRequestMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequestMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequestMessage proto.InternalMessageInfo

func (m *TransactionRequestMessage) GetTransactionHashes() [][]byte {
	if m != nil {
		return m.TransactionHashes
	}
	return nil
}

func (m *TransactionRequestMessage) GetCurrentBlockHash() []byte {
	if m != nil {
		return m.CurrentBlockHash
	}
	return nil
}

func (m *TransactionRequestMessage) GetBlockHeight() uint64 {
	if m != nil && m.BlockHeight != nil {
		return *m.BlockHeight
	}
	return 0
}

func (m *TransactionRequestMessage) GetBlockQn() uint64 {
	if m != nil && m.BlockQn != nil {
		return *m.BlockQn
	}
	return 0
}

type TransactionSlice struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TransactionSlice) Reset()         { *m = TransactionSlice{} }
func (m *TransactionSlice) String() string { return proto.CompactTextString(m) }
func (*TransactionSlice) ProtoMessage()    {}
func (*TransactionSlice) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{3}
}
func (m *TransactionSlice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionSlice.Unmarshal(m, b)
}
func (m *TransactionSlice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionSlice.Marshal(b, m, deterministic)
}
func (dst *TransactionSlice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionSlice.Merge(dst, src)
}
func (m *TransactionSlice) XXX_Size() int {
	return xxx_messageInfo_TransactionSlice.Size(m)
}
func (m *TransactionSlice) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionSlice.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionSlice proto.InternalMessageInfo

func (m *TransactionSlice) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockHeader struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=Hash" json:"Hash,omitempty"`
	Height               *uint64  `protobuf:"varint,2,opt,name=Height" json:"Height,omitempty"`
	PreHash              []byte   `protobuf:"bytes,3,opt,name=PreHash" json:"PreHash,omitempty"`
	PreTime              []byte   `protobuf:"bytes,4,opt,name=PreTime" json:"PreTime,omitempty"`
	QueueNumber          *uint64  `protobuf:"varint,5,opt,name=QueueNumber" json:"QueueNumber,omitempty"`
	TotalQN              *uint64  `protobuf:"varint,6,opt,name=TotalQN" json:"TotalQN,omitempty"`
	CurTime              []byte   `protobuf:"bytes,7,opt,name=CurTime" json:"CurTime,omitempty"`
	Castor               []byte   `protobuf:"bytes,8,opt,name=Castor" json:"Castor,omitempty"`
	GroupId              []byte   `protobuf:"bytes,9,opt,name=GroupId" json:"GroupId,omitempty"`
	Signature            []byte   `protobuf:"bytes,10,opt,name=Signature" json:"Signature,omitempty"`
	Nonce                *uint64  `protobuf:"varint,11,opt,name=Nonce" json:"Nonce,omitempty"`
	Transactions         *Hashes  `protobuf:"bytes,12,opt,name=transactions" json:"transactions,omitempty"`
	TxTree               []byte   `protobuf:"bytes,13,opt,name=TxTree" json:"TxTree,omitempty"`
	ReceiptTree          []byte   `protobuf:"bytes,14,opt,name=ReceiptTree" json:"ReceiptTree,omitempty"`
	StateTree            []byte   `protobuf:"bytes,15,opt,name=StateTree" json:"StateTree,omitempty"`
	ExtraData            []byte   `protobuf:"bytes,16,opt,name=ExtraData" json:"ExtraData,omitempty"`
	EvictedTxs           *Hashes  `protobuf:"bytes,17,opt,name=EvictedTxs" json:"EvictedTxs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{4}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (dst *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(dst, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockHeader) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *BlockHeader) GetPreHash() []byte {
	if m != nil {
		return m.PreHash
	}
	return nil
}

func (m *BlockHeader) GetPreTime() []byte {
	if m != nil {
		return m.PreTime
	}
	return nil
}

func (m *BlockHeader) GetQueueNumber() uint64 {
	if m != nil && m.QueueNumber != nil {
		return *m.QueueNumber
	}
	return 0
}

func (m *BlockHeader) GetTotalQN() uint64 {
	if m != nil && m.TotalQN != nil {
		return *m.TotalQN
	}
	return 0
}

func (m *BlockHeader) GetCurTime() []byte {
	if m != nil {
		return m.CurTime
	}
	return nil
}

func (m *BlockHeader) GetCastor() []byte {
	if m != nil {
		return m.Castor
	}
	return nil
}

func (m *BlockHeader) GetGroupId() []byte {
	if m != nil {
		return m.GroupId
	}
	return nil
}

func (m *BlockHeader) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *BlockHeader) GetNonce() uint64 {
	if m != nil && m.Nonce != nil {
		return *m.Nonce
	}
	return 0
}

func (m *BlockHeader) GetTransactions() *Hashes {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *BlockHeader) GetTxTree() []byte {
	if m != nil {
		return m.TxTree
	}
	return nil
}

func (m *BlockHeader) GetReceiptTree() []byte {
	if m != nil {
		return m.ReceiptTree
	}
	return nil
}

func (m *BlockHeader) GetStateTree() []byte {
	if m != nil {
		return m.StateTree
	}
	return nil
}

func (m *BlockHeader) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func (m *BlockHeader) GetEvictedTxs() *Hashes {
	if m != nil {
		return m.EvictedTxs
	}
	return nil
}

type BlockBody struct {
	BlockHash            []byte         `protobuf:"bytes,1,req,name=BlockHash" json:"BlockHash,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BlockBody) Reset()         { *m = BlockBody{} }
func (m *BlockBody) String() string { return proto.CompactTextString(m) }
func (*BlockBody) ProtoMessage()    {}
func (*BlockBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{5}
}
func (m *BlockBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockBody.Unmarshal(m, b)
}
func (m *BlockBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockBody.Marshal(b, m, deterministic)
}
func (dst *BlockBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockBody.Merge(dst, src)
}
func (m *BlockBody) XXX_Size() int {
	return xxx_messageInfo_BlockBody.Size(m)
}
func (m *BlockBody) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockBody.DiscardUnknown(m)
}

var xxx_messageInfo_BlockBody proto.InternalMessageInfo

func (m *BlockBody) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *BlockBody) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type Block struct {
	Header               *BlockHeader   `protobuf:"bytes,1,req,name=Header" json:"Header,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{6}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (dst *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(dst, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

type BlockSlice struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=Blocks" json:"Blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockSlice) Reset()         { *m = BlockSlice{} }
func (m *BlockSlice) String() string { return proto.CompactTextString(m) }
func (*BlockSlice) ProtoMessage()    {}
func (*BlockSlice) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{7}
}
func (m *BlockSlice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockSlice.Unmarshal(m, b)
}
func (m *BlockSlice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockSlice.Marshal(b, m, deterministic)
}
func (dst *BlockSlice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockSlice.Merge(dst, src)
}
func (m *BlockSlice) XXX_Size() int {
	return xxx_messageInfo_BlockSlice.Size(m)
}
func (m *BlockSlice) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockSlice.DiscardUnknown(m)
}

var xxx_messageInfo_BlockSlice proto.InternalMessageInfo

func (m *BlockSlice) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type Member struct {
	Id                   []byte   `protobuf:"bytes,1,req,name=Id" json:"Id,omitempty"`
	PubKey               []byte   `protobuf:"bytes,2,req,name=PubKey" json:"PubKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{8}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (dst *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(dst, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Member) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

type Group struct {
	Id                   []byte    `protobuf:"bytes,1,opt,name=Id" json:"Id,omitempty"`
	Members              []*Member `protobuf:"bytes,2,rep,name=Members" json:"Members,omitempty"`
	PubKey               []byte    `protobuf:"bytes,3,opt,name=PubKey" json:"PubKey,omitempty"`
	Parent               []byte    `protobuf:"bytes,4,opt,name=Parent" json:"Parent,omitempty"`
	Dummy                []byte    `protobuf:"bytes,5,opt,name=Dummy" json:"Dummy,omitempty"`
	Signature            []byte    `protobuf:"bytes,6,opt,name=Signature" json:"Signature,omitempty"`
	BeginHeight          *uint64   `protobuf:"varint,7,opt,name=BeginHeight" json:"BeginHeight,omitempty"`
	DismissHeight        *uint64   `protobuf:"varint,8,opt,name=DismissHeight" json:"DismissHeight,omitempty"`
	Authority            *uint64   `protobuf:"varint,9,opt,name=Authority" json:"Authority,omitempty"`
	Name                 []byte    `protobuf:"bytes,10,opt,name=Name" json:"Name,omitempty"`
	Extends              []byte    `protobuf:"bytes,11,opt,name=Extends" json:"Extends,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{9}
}
func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (dst *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(dst, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Group) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Group) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *Group) GetParent() []byte {
	if m != nil {
		return m.Parent
	}
	return nil
}

func (m *Group) GetDummy() []byte {
	if m != nil {
		return m.Dummy
	}
	return nil
}

func (m *Group) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *Group) GetBeginHeight() uint64 {
	if m != nil && m.BeginHeight != nil {
		return *m.BeginHeight
	}
	return 0
}

func (m *Group) GetDismissHeight() uint64 {
	if m != nil && m.DismissHeight != nil {
		return *m.DismissHeight
	}
	return 0
}

func (m *Group) GetAuthority() uint64 {
	if m != nil && m.Authority != nil {
		return *m.Authority
	}
	return 0
}

func (m *Group) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Group) GetExtends() []byte {
	if m != nil {
		return m.Extends
	}
	return nil
}

type GroupInfo struct {
	Group                *Group   `protobuf:"bytes,1,req,name=Group" json:"Group,omitempty"`
	IsTopGroup           *bool    `protobuf:"varint,2,req,name=IsTopGroup" json:"IsTopGroup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupInfo) Reset()         { *m = GroupInfo{} }
func (m *GroupInfo) String() string { return proto.CompactTextString(m) }
func (*GroupInfo) ProtoMessage()    {}
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{10}
}
func (m *GroupInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupInfo.Unmarshal(m, b)
}
func (m *GroupInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupInfo.Marshal(b, m, deterministic)
}
func (dst *GroupInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupInfo.Merge(dst, src)
}
func (m *GroupInfo) XXX_Size() int {
	return xxx_messageInfo_GroupInfo.Size(m)
}
func (m *GroupInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GroupInfo proto.InternalMessageInfo

func (m *GroupInfo) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *GroupInfo) GetIsTopGroup() bool {
	if m != nil && m.IsTopGroup != nil {
		return *m.IsTopGroup
	}
	return false
}

type GroupSlice struct {
	Groups               []*Group `protobuf:"bytes,1,rep,name=Groups" json:"Groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupSlice) Reset()         { *m = GroupSlice{} }
func (m *GroupSlice) String() string { return proto.CompactTextString(m) }
func (*GroupSlice) ProtoMessage()    {}
func (*GroupSlice) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{11}
}
func (m *GroupSlice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupSlice.Unmarshal(m, b)
}
func (m *GroupSlice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupSlice.Marshal(b, m, deterministic)
}
func (dst *GroupSlice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupSlice.Merge(dst, src)
}
func (m *GroupSlice) XXX_Size() int {
	return xxx_messageInfo_GroupSlice.Size(m)
}
func (m *GroupSlice) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupSlice.DiscardUnknown(m)
}

var xxx_messageInfo_GroupSlice proto.InternalMessageInfo

func (m *GroupSlice) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

type BlockRequestInfo struct {
	SourceHeight         *uint64  `protobuf:"varint,1,req,name=SourceHeight" json:"SourceHeight,omitempty"`
	SourceCurrentHash    []byte   `protobuf:"bytes,2,req,name=SourceCurrentHash" json:"SourceCurrentHash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequestInfo) Reset()         { *m = BlockRequestInfo{} }
func (m *BlockRequestInfo) String() string { return proto.CompactTextString(m) }
func (*BlockRequestInfo) ProtoMessage()    {}
func (*BlockRequestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{12}
}
func (m *BlockRequestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockRequestInfo.Unmarshal(m, b)
}
func (m *BlockRequestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockRequestInfo.Marshal(b, m, deterministic)
}
func (dst *BlockRequestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequestInfo.Merge(dst, src)
}
func (m *BlockRequestInfo) XXX_Size() int {
	return xxx_messageInfo_BlockRequestInfo.Size(m)
}
func (m *BlockRequestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequestInfo proto.InternalMessageInfo

func (m *BlockRequestInfo) GetSourceHeight() uint64 {
	if m != nil && m.SourceHeight != nil {
		return *m.SourceHeight
	}
	return 0
}

func (m *BlockRequestInfo) GetSourceCurrentHash() []byte {
	if m != nil {
		return m.SourceCurrentHash
	}
	return nil
}

type Hashes struct {
	Hashes               [][]byte `protobuf:"bytes,1,rep,name=hashes" json:"hashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Hashes) Reset()         { *m = Hashes{} }
func (m *Hashes) String() string { return proto.CompactTextString(m) }
func (*Hashes) ProtoMessage()    {}
func (*Hashes) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{13}
}
func (m *Hashes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Hashes.Unmarshal(m, b)
}
func (m *Hashes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Hashes.Marshal(b, m, deterministic)
}
func (dst *Hashes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Hashes.Merge(dst, src)
}
func (m *Hashes) XXX_Size() int {
	return xxx_messageInfo_Hashes.Size(m)
}
func (m *Hashes) XXX_DiscardUnknown() {
	xxx_messageInfo_Hashes.DiscardUnknown(m)
}

var xxx_messageInfo_Hashes proto.InternalMessageInfo

func (m *Hashes) GetHashes() [][]byte {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type BlockHash struct {
	Height               *uint64  `protobuf:"varint,1,req,name=Height" json:"Height,omitempty"`
	Hash                 []byte   `protobuf:"bytes,2,req,name=Hash" json:"Hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHash) Reset()         { *m = BlockHash{} }
func (m *BlockHash) String() string { return proto.CompactTextString(m) }
func (*BlockHash) ProtoMessage()    {}
func (*BlockHash) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{14}
}
func (m *BlockHash) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHash.Unmarshal(m, b)
}
func (m *BlockHash) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHash.Marshal(b, m, deterministic)
}
func (dst *BlockHash) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHash.Merge(dst, src)
}
func (m *BlockHash) XXX_Size() int {
	return xxx_messageInfo_BlockHash.Size(m)
}
func (m *BlockHash) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHash.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHash proto.InternalMessageInfo

func (m *BlockHash) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *BlockHash) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

type BlockChainPiece struct {
	BlockHashes          []*BlockHash `protobuf:"bytes,1,rep,name=BlockHashes" json:"BlockHashes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BlockChainPiece) Reset()         { *m = BlockChainPiece{} }
func (m *BlockChainPiece) String() string { return proto.CompactTextString(m) }
func (*BlockChainPiece) ProtoMessage()    {}
func (*BlockChainPiece) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{15}
}
func (m *BlockChainPiece) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockChainPiece.Unmarshal(m, b)
}
func (m *BlockChainPiece) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockChainPiece.Marshal(b, m, deterministic)
}
func (dst *BlockChainPiece) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockChainPiece.Merge(dst, src)
}
func (m *BlockChainPiece) XXX_Size() int {
	return xxx_messageInfo_BlockChainPiece.Size(m)
}
func (m *BlockChainPiece) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockChainPiece.DiscardUnknown(m)
}

var xxx_messageInfo_BlockChainPiece proto.InternalMessageInfo

func (m *BlockChainPiece) GetBlockHashes() []*BlockHash {
	if m != nil {
		return m.BlockHashes
	}
	return nil
}

type BlockInfo struct {
	Block                *Block           `protobuf:"bytes,1,opt,name=Block" json:"Block,omitempty"`
	ChainPiece           *BlockChainPiece `protobuf:"bytes,2,opt,name=ChainPiece" json:"ChainPiece,omitempty"`
	IsTopBlock           *bool            `protobuf:"varint,3,opt,name=IsTopBlock" json:"IsTopBlock,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BlockInfo) Reset()         { *m = BlockInfo{} }
func (m *BlockInfo) String() string { return proto.CompactTextString(m) }
func (*BlockInfo) ProtoMessage()    {}
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{16}
}
func (m *BlockInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockInfo.Unmarshal(m, b)
}
func (m *BlockInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockInfo.Marshal(b, m, deterministic)
}
func (dst *BlockInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockInfo.Merge(dst, src)
}
func (m *BlockInfo) XXX_Size() int {
	return xxx_messageInfo_BlockInfo.Size(m)
}
func (m *BlockInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlockInfo proto.InternalMessageInfo

func (m *BlockInfo) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *BlockInfo) GetChainPiece() *BlockChainPiece {
	if m != nil {
		return m.ChainPiece
	}
	return nil
}

func (m *BlockInfo) GetIsTopBlock() bool {
	if m != nil && m.IsTopBlock != nil {
		return *m.IsTopBlock
	}
	return false
}

type BlockHashesReq struct {
	Height               *uint64  `protobuf:"varint,1,req,name=Height" json:"Height,omitempty"`
	Length               *uint64  `protobuf:"varint,2,req,name=Length" json:"Length,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHashesReq) Reset()         { *m = BlockHashesReq{} }
func (m *BlockHashesReq) String() string { return proto.CompactTextString(m) }
func (*BlockHashesReq) ProtoMessage()    {}
func (*BlockHashesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{17}
}
func (m *BlockHashesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHashesReq.Unmarshal(m, b)
}
func (m *BlockHashesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHashesReq.Marshal(b, m, deterministic)
}
func (dst *BlockHashesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHashesReq.Merge(dst, src)
}
func (m *BlockHashesReq) XXX_Size() int {
	return xxx_messageInfo_BlockHashesReq.Size(m)
}
func (m *BlockHashesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHashesReq.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHashesReq proto.InternalMessageInfo

func (m *BlockHashesReq) GetHeight() uint64 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *BlockHashesReq) GetLength() uint64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

type SignData struct {
	DataHash             []byte   `protobuf:"bytes,1,req,name=DataHash" json:"DataHash,omitempty"`
	DataSign             []byte   `protobuf:"bytes,2,req,name=DataSign" json:"DataSign,omitempty"`
	SignMember           []byte   `protobuf:"bytes,3,req,name=SignMember" json:"SignMember,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignData) Reset()         { *m = SignData{} }
func (m *SignData) String() string { return proto.CompactTextString(m) }
func (*SignData) ProtoMessage()    {}
func (*SignData) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{18}
}
func (m *SignData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignData.Unmarshal(m, b)
}
func (m *SignData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignData.Marshal(b, m, deterministic)
}
func (dst *SignData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignData.Merge(dst, src)
}
func (m *SignData) XXX_Size() int {
	return xxx_messageInfo_SignData.Size(m)
}
func (m *SignData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignData.DiscardUnknown(m)
}

var xxx_messageInfo_SignData proto.InternalMessageInfo

func (m *SignData) GetDataHash() []byte {
	if m != nil {
		return m.DataHash
	}
	return nil
}

func (m *SignData) GetDataSign() []byte {
	if m != nil {
		return m.DataSign
	}
	return nil
}

func (m *SignData) GetSignMember() []byte {
	if m != nil {
		return m.SignMember
	}
	return nil
}

type ConsensusGroupInitSummary struct {
	ParentID             []byte   `protobuf:"bytes,1,req,name=ParentID" json:"ParentID,omitempty"`
	PrevGroupID          []byte   `protobuf:"bytes,2,req,name=PrevGroupID" json:"PrevGroupID,omitempty"`
	Authority            *uint64  `protobuf:"varint,3,req,name=Authority" json:"Authority,omitempty"`
	Name                 []byte   `protobuf:"bytes,4,req,name=Name" json:"Name,omitempty"`
	DummyID              []byte   `protobuf:"bytes,5,req,name=DummyID" json:"DummyID,omitempty"`
	Members              *uint64  `protobuf:"varint,6,req,name=Members" json:"Members,omitempty"`
	BeginTime            []byte   `protobuf:"bytes,7,req,name=BeginTime" json:"BeginTime,omitempty"`
	MemberHash           []byte   `protobuf:"bytes,8,req,name=MemberHash" json:"MemberHash,omitempty"`
	Signature            []byte   `protobuf:"bytes,9,req,name=Signature" json:"Signature,omitempty"`
	GetReadyHeight       *uint64  `protobuf:"varint,10,req,name=GetReadyHeight" json:"GetReadyHeight,omitempty"`
	BeginCastHeight      *uint64  `protobuf:"varint,11,req,name=BeginCastHeight" json:"BeginCastHeight,omitempty"`
	DismissHeight        *uint64  `protobuf:"varint,12,req,name=DismissHeight" json:"DismissHeight,omitempty"`
	TopHeight            *uint64  `protobuf:"varint,13,req,name=TopHeight" json:"TopHeight,omitempty"`
	Extends              []byte   `protobuf:"bytes,14,req,name=Extends" json:"Extends,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsensusGroupInitSummary) Reset()         { *m = ConsensusGroupInitSummary{} }
func (m *ConsensusGroupInitSummary) String() string { return proto.CompactTextString(m) }
func (*ConsensusGroupInitSummary) ProtoMessage()    {}
func (*ConsensusGroupInitSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{19}
}
func (m *ConsensusGroupInitSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusGroupInitSummary.Unmarshal(m, b)
}
func (m *ConsensusGroupInitSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusGroupInitSummary.Marshal(b, m, deterministic)
}
func (dst *ConsensusGroupInitSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusGroupInitSummary.Merge(dst, src)
}
func (m *ConsensusGroupInitSummary) XXX_Size() int {
	return xxx_messageInfo_ConsensusGroupInitSummary.Size(m)
}
func (m *ConsensusGroupInitSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusGroupInitSummary.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusGroupInitSummary proto.InternalMessageInfo

func (m *ConsensusGroupInitSummary) GetParentID() []byte {
	if m != nil {
		return m.ParentID
	}
	return nil
}

func (m *ConsensusGroupInitSummary) GetPrevGroupID() []byte {
	if m != nil {
		return m.PrevGroupID
	}
	return nil
}

func (m *ConsensusGroupInitSummary) GetAuthority() uint64 {
	if m != nil && m.Authority != nil {
		return *m.Authority
	}
	return 0
}

func (m *ConsensusGroupInitSummary) GetName() []byte {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ConsensusGroupInitSummary) GetDummyID() []byte {
	if m != nil {
		return m.DummyID
	}
	return nil
}

func (m *ConsensusGroupInitSummary) GetMembers() uint64 {
	if m != nil && m.Members != nil {
		return *m.Members
	}
	return 0
}

func (m *ConsensusGroupInitSummary) GetBeginTime() []byte {
	if m != nil {
		return m.BeginTime
	}
	return nil
}

func (m *ConsensusGroupInitSummary) GetMemberHash() []byte {
	if m != nil {
		return m.MemberHash
	}
	return nil
}

func (m *ConsensusGroupInitSummary) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *ConsensusGroupInitSummary) GetGetReadyHeight() uint64 {
	if m != nil && m.GetReadyHeight != nil {
		return *m.GetReadyHeight
	}
	return 0
}

func (m *ConsensusGroupInitSummary) GetBeginCastHeight() uint64 {
	if m != nil && m.BeginCastHeight != nil {
		return *m.BeginCastHeight
	}
	return 0
}

func (m *ConsensusGroupInitSummary) GetDismissHeight() uint64 {
	if m != nil && m.DismissHeight != nil {
		return *m.DismissHeight
	}
	return 0
}

func (m *ConsensusGroupInitSummary) GetTopHeight() uint64 {
	if m != nil && m.TopHeight != nil {
		return *m.TopHeight
	}
	return 0
}

func (m *ConsensusGroupInitSummary) GetExtends() []byte {
	if m != nil {
		return m.Extends
	}
	return nil
}

type PubKeyInfo struct {
	ID                   []byte   `protobuf:"bytes,1,req,name=ID" json:"ID,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,req,name=PublicKey" json:"PublicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PubKeyInfo) Reset()         { *m = PubKeyInfo{} }
func (m *PubKeyInfo) String() string { return proto.CompactTextString(m) }
func (*PubKeyInfo) ProtoMessage()    {}
func (*PubKeyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{20}
}
func (m *PubKeyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubKeyInfo.Unmarshal(m, b)
}
func (m *PubKeyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubKeyInfo.Marshal(b, m, deterministic)
}
func (dst *PubKeyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubKeyInfo.Merge(dst, src)
}
func (m *PubKeyInfo) XXX_Size() int {
	return xxx_messageInfo_PubKeyInfo.Size(m)
}
func (m *PubKeyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PubKeyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PubKeyInfo proto.InternalMessageInfo

func (m *PubKeyInfo) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *PubKeyInfo) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

type ConsensusGroupRawMessage struct {
	ConsensusGroupInitSummary *ConsensusGroupInitSummary `protobuf:"bytes,1,req,name=ConsensusGroupInitSummary" json:"ConsensusGroupInitSummary,omitempty"`
	Ids                       []*PubKeyInfo              `protobuf:"bytes,2,rep,name=Ids" json:"Ids,omitempty"`
	Sign                      *SignData                  `protobuf:"bytes,3,req,name=sign" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                   `json:"-"`
	XXX_unrecognized          []byte                     `json:"-"`
	XXX_sizecache             int32                      `json:"-"`
}

func (m *ConsensusGroupRawMessage) Reset()         { *m = ConsensusGroupRawMessage{} }
func (m *ConsensusGroupRawMessage) String() string { return proto.CompactTextString(m) }
func (*ConsensusGroupRawMessage) ProtoMessage()    {}
func (*ConsensusGroupRawMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{21}
}
func (m *ConsensusGroupRawMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusGroupRawMessage.Unmarshal(m, b)
}
func (m *ConsensusGroupRawMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusGroupRawMessage.Marshal(b, m, deterministic)
}
func (dst *ConsensusGroupRawMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusGroupRawMessage.Merge(dst, src)
}
func (m *ConsensusGroupRawMessage) XXX_Size() int {
	return xxx_messageInfo_ConsensusGroupRawMessage.Size(m)
}
func (m *ConsensusGroupRawMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusGroupRawMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusGroupRawMessage proto.InternalMessageInfo

func (m *ConsensusGroupRawMessage) GetConsensusGroupInitSummary() *ConsensusGroupInitSummary {
	if m != nil {
		return m.ConsensusGroupInitSummary
	}
	return nil
}

func (m *ConsensusGroupRawMessage) GetIds() []*PubKeyInfo {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ConsensusGroupRawMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type SharePiece struct {
	Seckey               []byte   `protobuf:"bytes,1,req,name=Seckey" json:"Seckey,omitempty"`
	Pubkey               []byte   `protobuf:"bytes,2,req,name=Pubkey" json:"Pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SharePiece) Reset()         { *m = SharePiece{} }
func (m *SharePiece) String() string { return proto.CompactTextString(m) }
func (*SharePiece) ProtoMessage()    {}
func (*SharePiece) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{22}
}
func (m *SharePiece) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SharePiece.Unmarshal(m, b)
}
func (m *SharePiece) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SharePiece.Marshal(b, m, deterministic)
}
func (dst *SharePiece) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SharePiece.Merge(dst, src)
}
func (m *SharePiece) XXX_Size() int {
	return xxx_messageInfo_SharePiece.Size(m)
}
func (m *SharePiece) XXX_DiscardUnknown() {
	xxx_messageInfo_SharePiece.DiscardUnknown(m)
}

var xxx_messageInfo_SharePiece proto.InternalMessageInfo

func (m *SharePiece) GetSeckey() []byte {
	if m != nil {
		return m.Seckey
	}
	return nil
}

func (m *SharePiece) GetPubkey() []byte {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

type ConsensusSharePieceMessage struct {
	GISHash              []byte      `protobuf:"bytes,1,req,name=GISHash" json:"GISHash,omitempty"`
	DummyID              []byte      `protobuf:"bytes,2,req,name=DummyID" json:"DummyID,omitempty"`
	Dest                 []byte      `protobuf:"bytes,3,req,name=Dest" json:"Dest,omitempty"`
	SharePiece           *SharePiece `protobuf:"bytes,4,req,name=SharePiece" json:"SharePiece,omitempty"`
	Sign                 *SignData   `protobuf:"bytes,5,req,name=Sign" json:"Sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ConsensusSharePieceMessage) Reset()         { *m = ConsensusSharePieceMessage{} }
func (m *ConsensusSharePieceMessage) String() string { return proto.CompactTextString(m) }
func (*ConsensusSharePieceMessage) ProtoMessage()    {}
func (*ConsensusSharePieceMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{23}
}
func (m *ConsensusSharePieceMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusSharePieceMessage.Unmarshal(m, b)
}
func (m *ConsensusSharePieceMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusSharePieceMessage.Marshal(b, m, deterministic)
}
func (dst *ConsensusSharePieceMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusSharePieceMessage.Merge(dst, src)
}
func (m *ConsensusSharePieceMessage) XXX_Size() int {
	return xxx_messageInfo_ConsensusSharePieceMessage.Size(m)
}
func (m *ConsensusSharePieceMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusSharePieceMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusSharePieceMessage proto.InternalMessageInfo

func (m *ConsensusSharePieceMessage) GetGISHash() []byte {
	if m != nil {
		return m.GISHash
	}
	return nil
}

func (m *ConsensusSharePieceMessage) GetDummyID() []byte {
	if m != nil {
		return m.DummyID
	}
	return nil
}

func (m *ConsensusSharePieceMessage) GetDest() []byte {
	if m != nil {
		return m.Dest
	}
	return nil
}

func (m *ConsensusSharePieceMessage) GetSharePiece() *SharePiece {
	if m != nil {
		return m.SharePiece
	}
	return nil
}

func (m *ConsensusSharePieceMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ConsensusSignPubKeyMessage struct {
	GISHash              []byte    `protobuf:"bytes,1,req,name=GISHash" json:"GISHash,omitempty"`
	DummyID              []byte    `protobuf:"bytes,2,req,name=DummyID" json:"DummyID,omitempty"`
	SignPK               []byte    `protobuf:"bytes,3,req,name=SignPK" json:"SignPK,omitempty"`
	SignData             *SignData `protobuf:"bytes,4,req,name=SignData" json:"SignData,omitempty"`
	GISSign              []byte    `protobuf:"bytes,5,req,name=GISSign" json:"GISSign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConsensusSignPubKeyMessage) Reset()         { *m = ConsensusSignPubKeyMessage{} }
func (m *ConsensusSignPubKeyMessage) String() string { return proto.CompactTextString(m) }
func (*ConsensusSignPubKeyMessage) ProtoMessage()    {}
func (*ConsensusSignPubKeyMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{24}
}
func (m *ConsensusSignPubKeyMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusSignPubKeyMessage.Unmarshal(m, b)
}
func (m *ConsensusSignPubKeyMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusSignPubKeyMessage.Marshal(b, m, deterministic)
}
func (dst *ConsensusSignPubKeyMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusSignPubKeyMessage.Merge(dst, src)
}
func (m *ConsensusSignPubKeyMessage) XXX_Size() int {
	return xxx_messageInfo_ConsensusSignPubKeyMessage.Size(m)
}
func (m *ConsensusSignPubKeyMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusSignPubKeyMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusSignPubKeyMessage proto.InternalMessageInfo

func (m *ConsensusSignPubKeyMessage) GetGISHash() []byte {
	if m != nil {
		return m.GISHash
	}
	return nil
}

func (m *ConsensusSignPubKeyMessage) GetDummyID() []byte {
	if m != nil {
		return m.DummyID
	}
	return nil
}

func (m *ConsensusSignPubKeyMessage) GetSignPK() []byte {
	if m != nil {
		return m.SignPK
	}
	return nil
}

func (m *ConsensusSignPubKeyMessage) GetSignData() *SignData {
	if m != nil {
		return m.SignData
	}
	return nil
}

func (m *ConsensusSignPubKeyMessage) GetGISSign() []byte {
	if m != nil {
		return m.GISSign
	}
	return nil
}

type StaticGroupSummary struct {
	GroupID              []byte                     `protobuf:"bytes,1,req,name=GroupID" json:"GroupID,omitempty"`
	GroupPK              []byte                     `protobuf:"bytes,2,req,name=GroupPK" json:"GroupPK,omitempty"`
	Gis                  *ConsensusGroupInitSummary `protobuf:"bytes,3,req,name=Gis" json:"Gis,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *StaticGroupSummary) Reset()         { *m = StaticGroupSummary{} }
func (m *StaticGroupSummary) String() string { return proto.CompactTextString(m) }
func (*StaticGroupSummary) ProtoMessage()    {}
func (*StaticGroupSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{25}
}
func (m *StaticGroupSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StaticGroupSummary.Unmarshal(m, b)
}
func (m *StaticGroupSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StaticGroupSummary.Marshal(b, m, deterministic)
}
func (dst *StaticGroupSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StaticGroupSummary.Merge(dst, src)
}
func (m *StaticGroupSummary) XXX_Size() int {
	return xxx_messageInfo_StaticGroupSummary.Size(m)
}
func (m *StaticGroupSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_StaticGroupSummary.DiscardUnknown(m)
}

var xxx_messageInfo_StaticGroupSummary proto.InternalMessageInfo

func (m *StaticGroupSummary) GetGroupID() []byte {
	if m != nil {
		return m.GroupID
	}
	return nil
}

func (m *StaticGroupSummary) GetGroupPK() []byte {
	if m != nil {
		return m.GroupPK
	}
	return nil
}

func (m *StaticGroupSummary) GetGis() *ConsensusGroupInitSummary {
	if m != nil {
		return m.Gis
	}
	return nil
}

type ConsensusGroupInitedMessage struct {
	StaticGroupSummary   *StaticGroupSummary `protobuf:"bytes,1,req,name=StaticGroupSummary" json:"StaticGroupSummary,omitempty"`
	Sign                 *SignData           `protobuf:"bytes,2,req,name=Sign" json:"Sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *ConsensusGroupInitedMessage) Reset()         { *m = ConsensusGroupInitedMessage{} }
func (m *ConsensusGroupInitedMessage) String() string { return proto.CompactTextString(m) }
func (*ConsensusGroupInitedMessage) ProtoMessage()    {}
func (*ConsensusGroupInitedMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{26}
}
func (m *ConsensusGroupInitedMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusGroupInitedMessage.Unmarshal(m, b)
}
func (m *ConsensusGroupInitedMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusGroupInitedMessage.Marshal(b, m, deterministic)
}
func (dst *ConsensusGroupInitedMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusGroupInitedMessage.Merge(dst, src)
}
func (m *ConsensusGroupInitedMessage) XXX_Size() int {
	return xxx_messageInfo_ConsensusGroupInitedMessage.Size(m)
}
func (m *ConsensusGroupInitedMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusGroupInitedMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusGroupInitedMessage proto.InternalMessageInfo

func (m *ConsensusGroupInitedMessage) GetStaticGroupSummary() *StaticGroupSummary {
	if m != nil {
		return m.StaticGroupSummary
	}
	return nil
}

func (m *ConsensusGroupInitedMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ConsensusCurrentMessage struct {
	GroupID              []byte    `protobuf:"bytes,1,opt,name=GroupID" json:"GroupID,omitempty"`
	PreHash              []byte    `protobuf:"bytes,2,req,name=PreHash" json:"PreHash,omitempty"`
	PreTime              []byte    `protobuf:"bytes,3,req,name=PreTime" json:"PreTime,omitempty"`
	BlockHeight          *uint64   `protobuf:"varint,4,req,name=BlockHeight" json:"BlockHeight,omitempty"`
	Sign                 *SignData `protobuf:"bytes,6,req,name=Sign" json:"Sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ConsensusCurrentMessage) Reset()         { *m = ConsensusCurrentMessage{} }
func (m *ConsensusCurrentMessage) String() string { return proto.CompactTextString(m) }
func (*ConsensusCurrentMessage) ProtoMessage()    {}
func (*ConsensusCurrentMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{27}
}
func (m *ConsensusCurrentMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusCurrentMessage.Unmarshal(m, b)
}
func (m *ConsensusCurrentMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusCurrentMessage.Marshal(b, m, deterministic)
}
func (dst *ConsensusCurrentMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusCurrentMessage.Merge(dst, src)
}
func (m *ConsensusCurrentMessage) XXX_Size() int {
	return xxx_messageInfo_ConsensusCurrentMessage.Size(m)
}
func (m *ConsensusCurrentMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusCurrentMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusCurrentMessage proto.InternalMessageInfo

func (m *ConsensusCurrentMessage) GetGroupID() []byte {
	if m != nil {
		return m.GroupID
	}
	return nil
}

func (m *ConsensusCurrentMessage) GetPreHash() []byte {
	if m != nil {
		return m.PreHash
	}
	return nil
}

func (m *ConsensusCurrentMessage) GetPreTime() []byte {
	if m != nil {
		return m.PreTime
	}
	return nil
}

func (m *ConsensusCurrentMessage) GetBlockHeight() uint64 {
	if m != nil && m.BlockHeight != nil {
		return *m.BlockHeight
	}
	return 0
}

func (m *ConsensusCurrentMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ConsensusBlockMessageBase struct {
	Bh                   *BlockHeader `protobuf:"bytes,1,req,name=Bh" json:"Bh,omitempty"`
	GroupID              []byte       `protobuf:"bytes,2,opt,name=GroupID" json:"GroupID,omitempty"`
	Sign                 *SignData    `protobuf:"bytes,3,req,name=Sign" json:"Sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConsensusBlockMessageBase) Reset()         { *m = ConsensusBlockMessageBase{} }
func (m *ConsensusBlockMessageBase) String() string { return proto.CompactTextString(m) }
func (*ConsensusBlockMessageBase) ProtoMessage()    {}
func (*ConsensusBlockMessageBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{28}
}
func (m *ConsensusBlockMessageBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusBlockMessageBase.Unmarshal(m, b)
}
func (m *ConsensusBlockMessageBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusBlockMessageBase.Marshal(b, m, deterministic)
}
func (dst *ConsensusBlockMessageBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusBlockMessageBase.Merge(dst, src)
}
func (m *ConsensusBlockMessageBase) XXX_Size() int {
	return xxx_messageInfo_ConsensusBlockMessageBase.Size(m)
}
func (m *ConsensusBlockMessageBase) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusBlockMessageBase.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusBlockMessageBase proto.InternalMessageInfo

func (m *ConsensusBlockMessageBase) GetBh() *BlockHeader {
	if m != nil {
		return m.Bh
	}
	return nil
}

func (m *ConsensusBlockMessageBase) GetGroupID() []byte {
	if m != nil {
		return m.GroupID
	}
	return nil
}

func (m *ConsensusBlockMessageBase) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ConsensusBlockMessage struct {
	Block                *Block   `protobuf:"bytes,1,req,name=Block" json:"Block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsensusBlockMessage) Reset()         { *m = ConsensusBlockMessage{} }
func (m *ConsensusBlockMessage) String() string { return proto.CompactTextString(m) }
func (*ConsensusBlockMessage) ProtoMessage()    {}
func (*ConsensusBlockMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{29}
}
func (m *ConsensusBlockMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusBlockMessage.Unmarshal(m, b)
}
func (m *ConsensusBlockMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusBlockMessage.Marshal(b, m, deterministic)
}
func (dst *ConsensusBlockMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusBlockMessage.Merge(dst, src)
}
func (m *ConsensusBlockMessage) XXX_Size() int {
	return xxx_messageInfo_ConsensusBlockMessage.Size(m)
}
func (m *ConsensusBlockMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusBlockMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusBlockMessage proto.InternalMessageInfo

func (m *ConsensusBlockMessage) GetBlock() *Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type ConsensusCreateGroupRawMessage struct {
	ConsensusGroupInitSummary *ConsensusGroupInitSummary `protobuf:"bytes,1,req,name=ConsensusGroupInitSummary" json:"ConsensusGroupInitSummary,omitempty"`
	Ids                       [][]byte                   `protobuf:"bytes,2,rep,name=Ids" json:"Ids,omitempty"`
	Sign                      *SignData                  `protobuf:"bytes,3,req,name=sign" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                   `json:"-"`
	XXX_unrecognized          []byte                     `json:"-"`
	XXX_sizecache             int32                      `json:"-"`
}

func (m *ConsensusCreateGroupRawMessage) Reset()         { *m = ConsensusCreateGroupRawMessage{} }
func (m *ConsensusCreateGroupRawMessage) String() string { return proto.CompactTextString(m) }
func (*ConsensusCreateGroupRawMessage) ProtoMessage()    {}
func (*ConsensusCreateGroupRawMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{30}
}
func (m *ConsensusCreateGroupRawMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusCreateGroupRawMessage.Unmarshal(m, b)
}
func (m *ConsensusCreateGroupRawMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusCreateGroupRawMessage.Marshal(b, m, deterministic)
}
func (dst *ConsensusCreateGroupRawMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusCreateGroupRawMessage.Merge(dst, src)
}
func (m *ConsensusCreateGroupRawMessage) XXX_Size() int {
	return xxx_messageInfo_ConsensusCreateGroupRawMessage.Size(m)
}
func (m *ConsensusCreateGroupRawMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusCreateGroupRawMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusCreateGroupRawMessage proto.InternalMessageInfo

func (m *ConsensusCreateGroupRawMessage) GetConsensusGroupInitSummary() *ConsensusGroupInitSummary {
	if m != nil {
		return m.ConsensusGroupInitSummary
	}
	return nil
}

func (m *ConsensusCreateGroupRawMessage) GetIds() [][]byte {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ConsensusCreateGroupRawMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

type ConsensusCreateGroupSignMessage struct {
	ConsensusGroupInitSummary *ConsensusGroupInitSummary `protobuf:"bytes,1,req,name=ConsensusGroupInitSummary" json:"ConsensusGroupInitSummary,omitempty"`
	Sign                      *SignData                  `protobuf:"bytes,2,req,name=sign" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                   `json:"-"`
	XXX_unrecognized          []byte                     `json:"-"`
	XXX_sizecache             int32                      `json:"-"`
}

func (m *ConsensusCreateGroupSignMessage) Reset()         { *m = ConsensusCreateGroupSignMessage{} }
func (m *ConsensusCreateGroupSignMessage) String() string { return proto.CompactTextString(m) }
func (*ConsensusCreateGroupSignMessage) ProtoMessage()    {}
func (*ConsensusCreateGroupSignMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_tas_40975c80b361d501, []int{31}
}
func (m *ConsensusCreateGroupSignMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusCreateGroupSignMessage.Unmarshal(m, b)
}
func (m *ConsensusCreateGroupSignMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusCreateGroupSignMessage.Marshal(b, m, deterministic)
}
func (dst *ConsensusCreateGroupSignMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusCreateGroupSignMessage.Merge(dst, src)
}
func (m *ConsensusCreateGroupSignMessage) XXX_Size() int {
	return xxx_messageInfo_ConsensusCreateGroupSignMessage.Size(m)
}
func (m *ConsensusCreateGroupSignMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusCreateGroupSignMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusCreateGroupSignMessage proto.InternalMessageInfo

func (m *ConsensusCreateGroupSignMessage) GetConsensusGroupInitSummary() *ConsensusGroupInitSummary {
	if m != nil {
		return m.ConsensusGroupInitSummary
	}
	return nil
}

func (m *ConsensusCreateGroupSignMessage) GetSign() *SignData {
	if m != nil {
		return m.Sign
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "tas.middleware.pb.Message")
	proto.RegisterType((*Transaction)(nil), "tas.middleware.pb.Transaction")
	proto.RegisterType((*TransactionRequestMessage)(nil), "tas.middleware.pb.TransactionRequestMessage")
	proto.RegisterType((*TransactionSlice)(nil), "tas.middleware.pb.TransactionSlice")
	proto.RegisterType((*BlockHeader)(nil), "tas.middleware.pb.BlockHeader")
	proto.RegisterType((*BlockBody)(nil), "tas.middleware.pb.BlockBody")
	proto.RegisterType((*Block)(nil), "tas.middleware.pb.Block")
	proto.RegisterType((*BlockSlice)(nil), "tas.middleware.pb.BlockSlice")
	proto.RegisterType((*Member)(nil), "tas.middleware.pb.Member")
	proto.RegisterType((*Group)(nil), "tas.middleware.pb.Group")
	proto.RegisterType((*GroupInfo)(nil), "tas.middleware.pb.GroupInfo")
	proto.RegisterType((*GroupSlice)(nil), "tas.middleware.pb.GroupSlice")
	proto.RegisterType((*BlockRequestInfo)(nil), "tas.middleware.pb.BlockRequestInfo")
	proto.RegisterType((*Hashes)(nil), "tas.middleware.pb.Hashes")
	proto.RegisterType((*BlockHash)(nil), "tas.middleware.pb.BlockHash")
	proto.RegisterType((*BlockChainPiece)(nil), "tas.middleware.pb.BlockChainPiece")
	proto.RegisterType((*BlockInfo)(nil), "tas.middleware.pb.BlockInfo")
	proto.RegisterType((*BlockHashesReq)(nil), "tas.middleware.pb.BlockHashesReq")
	proto.RegisterType((*SignData)(nil), "tas.middleware.pb.SignData")
	proto.RegisterType((*ConsensusGroupInitSummary)(nil), "tas.middleware.pb.ConsensusGroupInitSummary")
	proto.RegisterType((*PubKeyInfo)(nil), "tas.middleware.pb.PubKeyInfo")
	proto.RegisterType((*ConsensusGroupRawMessage)(nil), "tas.middleware.pb.ConsensusGroupRawMessage")
	proto.RegisterType((*SharePiece)(nil), "tas.middleware.pb.SharePiece")
	proto.RegisterType((*ConsensusSharePieceMessage)(nil), "tas.middleware.pb.ConsensusSharePieceMessage")
	proto.RegisterType((*ConsensusSignPubKeyMessage)(nil), "tas.middleware.pb.ConsensusSignPubKeyMessage")
	proto.RegisterType((*StaticGroupSummary)(nil), "tas.middleware.pb.StaticGroupSummary")
	proto.RegisterType((*ConsensusGroupInitedMessage)(nil), "tas.middleware.pb.ConsensusGroupInitedMessage")
	proto.RegisterType((*ConsensusCurrentMessage)(nil), "tas.middleware.pb.ConsensusCurrentMessage")
	proto.RegisterType((*ConsensusBlockMessageBase)(nil), "tas.middleware.pb.ConsensusBlockMessageBase")
	proto.RegisterType((*ConsensusBlockMessage)(nil), "tas.middleware.pb.ConsensusBlockMessage")
	proto.RegisterType((*ConsensusCreateGroupRawMessage)(nil), "tas.middleware.pb.ConsensusCreateGroupRawMessage")
	proto.RegisterType((*ConsensusCreateGroupSignMessage)(nil), "tas.middleware.pb.ConsensusCreateGroupSignMessage")
}

func init() { proto.RegisterFile("tas.proto", fileDescriptor_tas_40975c80b361d501) }

var fileDescriptor_tas_40975c80b361d501 = []byte{
	// 1565 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x57, 0x4d, 0x6f, 0x1c, 0x45,
	0x13, 0xd6, 0xcc, 0xae, 0xd7, 0x76, 0xed, 0xda, 0x71, 0x46, 0xef, 0x6b, 0x26, 0x1f, 0x84, 0xd5,
	0x08, 0x90, 0x85, 0x22, 0x27, 0x32, 0x12, 0x11, 0x88, 0x44, 0x60, 0x6f, 0x64, 0x56, 0x49, 0x8c,
	0xdd, 0x5e, 0x72, 0xe1, 0x34, 0xde, 0x69, 0xbc, 0x83, 0xbd, 0x33, 0xce, 0x7c, 0x24, 0xde, 0x33,
	0x17, 0x2e, 0x5c, 0x91, 0x38, 0x71, 0xe2, 0x07, 0x70, 0x05, 0x89, 0x13, 0x37, 0x0e, 0x5c, 0xf8,
	0x11, 0xfc, 0x0c, 0x54, 0xd5, 0xd5, 0x33, 0x3d, 0xbb, 0x63, 0xb3, 0x04, 0xa4, 0x9c, 0x76, 0xea,
	0xa3, 0xbb, 0xab, 0xaa, 0x9f, 0xa7, 0xaa, 0x17, 0x96, 0x33, 0x3f, 0xdd, 0x3c, 0x4b, 0xe2, 0x2c,
	0x76, 0xae, 0xe2, 0xe7, 0x38, 0x0c, 0x82, 0x53, 0xf9, 0xc2, 0x4f, 0xe4, 0xe6, 0xd9, 0x91, 0xf7,
	0x29, 0x2c, 0x3e, 0x91, 0x69, 0xea, 0x1f, 0x4b, 0xc7, 0x81, 0xe6, 0x4e, 0x1c, 0x48, 0xd7, 0xea,
	0xda, 0x1b, 0x2b, 0x82, 0xbe, 0x9d, 0x9b, 0xb0, 0x7c, 0x18, 0x1e, 0x47, 0x7e, 0x96, 0x27, 0xd2,
	0xb5, 0xbb, 0xd6, 0x46, 0x47, 0x94, 0x0a, 0x5c, 0xb1, 0x1d, 0x07, 0x13, 0xb7, 0x41, 0x06, 0xfa,
	0xf6, 0xbe, 0xb1, 0xa1, 0x3d, 0x48, 0xfc, 0x28, 0xf5, 0x87, 0x59, 0x18, 0x47, 0xe8, 0xd3, 0xf3,
	0x33, 0xdf, 0xb5, 0x94, 0x0f, 0x7e, 0x3b, 0xff, 0x83, 0x85, 0xa7, 0xfe, 0x69, 0xae, 0x76, 0x6c,
	0x0a, 0x25, 0xa0, 0x76, 0x2f, 0x8e, 0x86, 0xd2, 0x6d, 0x74, 0x6d, 0xd4, 0x92, 0xe0, 0xac, 0x43,
	0xeb, 0x30, 0xce, 0x93, 0xa1, 0x74, 0x9b, 0x5d, 0x7b, 0xa3, 0x23, 0x58, 0x42, 0xfd, 0xc0, 0x4f,
	0x8e, 0x65, 0xe6, 0x2e, 0xd0, 0xce, 0x2c, 0x39, 0xd7, 0x61, 0x69, 0xd7, 0x4f, 0x1f, 0x87, 0xe3,
	0x30, 0x73, 0x5b, 0xb4, 0x51, 0x21, 0xb3, 0x6d, 0x3f, 0x09, 0x87, 0xd2, 0x5d, 0x2c, 0x6c, 0x24,
	0x63, 0x9c, 0x9f, 0xf8, 0xe9, 0xc8, 0x5d, 0xa2, 0x53, 0xe8, 0x1b, 0xb3, 0x7f, 0x78, 0x9e, 0x25,
	0x3e, 0x25, 0xb0, 0xac, 0xb2, 0x2f, 0x14, 0xce, 0x9b, 0xb0, 0x52, 0x08, 0x83, 0xc9, 0x99, 0x74,
	0xa1, 0x6b, 0x6d, 0x2c, 0x88, 0xaa, 0xd2, 0xfb, 0xd1, 0x82, 0x6b, 0x46, 0x3d, 0x84, 0x7c, 0x96,
	0xcb, 0x34, 0xd3, 0x35, 0xbf, 0x0d, 0x57, 0x0d, 0x23, 0x1e, 0x2a, 0x53, 0xd7, 0xea, 0x36, 0x36,
	0x3a, 0x62, 0xd6, 0xe0, 0xbc, 0x03, 0x6b, 0x3b, 0x79, 0x92, 0xc8, 0x28, 0xdb, 0x3e, 0x8d, 0x87,
	0x27, 0x14, 0xaf, 0x4d, 0xf1, 0xce, 0xe8, 0x9d, 0x2e, 0xb4, 0x95, 0x20, 0xc3, 0xe3, 0x51, 0xc6,
	0x35, 0x35, 0x55, 0x8e, 0x0b, 0x8b, 0x24, 0x1e, 0x44, 0x54, 0xda, 0xa6, 0xd0, 0xa2, 0xf7, 0x14,
	0xd6, 0x8c, 0xc3, 0x0f, 0x4f, 0xb1, 0x3e, 0xdb, 0xd0, 0xc9, 0x4a, 0x9d, 0x0a, 0xb2, 0xbd, 0x75,
	0x6b, 0x73, 0x06, 0x52, 0x9b, 0x66, 0xb6, 0x95, 0x35, 0xde, 0x77, 0xcd, 0x22, 0x28, 0x3f, 0x90,
	0x49, 0x51, 0x73, 0xc6, 0x06, 0xc5, 0xbd, 0x0e, 0x2d, 0x0e, 0x59, 0x81, 0xa3, 0x55, 0x46, 0xbb,
	0x9f, 0x48, 0x72, 0x57, 0x70, 0xd3, 0x22, 0x5b, 0x06, 0xe1, 0x18, 0x21, 0xa2, 0x2d, 0x28, 0x62,
	0x0d, 0x0e, 0x72, 0x99, 0xcb, 0xbd, 0x7c, 0x7c, 0x24, 0x13, 0x02, 0x4a, 0x53, 0x98, 0x2a, 0x5c,
	0x3b, 0x88, 0x33, 0xff, 0xf4, 0x60, 0xcf, 0x6d, 0x91, 0x55, 0x8b, 0x68, 0xd9, 0xc9, 0x13, 0xda,
	0x75, 0x51, 0xed, 0xca, 0x22, 0x46, 0xb8, 0xe3, 0xa7, 0x59, 0x9c, 0xb8, 0x4b, 0x0a, 0x79, 0x4a,
	0xc2, 0x15, 0xbb, 0x49, 0x9c, 0x9f, 0xf5, 0x03, 0xc6, 0x8a, 0x16, 0xab, 0x2c, 0x82, 0x69, 0x16,
	0x15, 0xb8, 0x6f, 0x2b, 0x36, 0x28, 0xdc, 0xdf, 0x9f, 0xaa, 0x77, 0xa7, 0x6b, 0x6d, 0xb4, 0xb7,
	0xae, 0xd5, 0xd4, 0x5b, 0x81, 0xa3, 0x5a, 0x6a, 0xa2, 0xc7, 0xf9, 0x20, 0x91, 0xd2, 0x5d, 0x61,
	0x7a, 0x90, 0x84, 0x25, 0x11, 0x72, 0x28, 0xc3, 0xb3, 0x8c, 0x8c, 0xab, 0x64, 0x34, 0x55, 0x14,
	0x6c, 0xe6, 0x67, 0x92, 0xec, 0x57, 0x38, 0x58, 0xad, 0xa8, 0x52, 0x62, 0x6d, 0x9a, 0x12, 0xef,
	0x03, 0x3c, 0x7c, 0x1e, 0x0e, 0x33, 0x19, 0x0c, 0xce, 0x53, 0xf7, 0xea, 0xdf, 0x85, 0x6c, 0x38,
	0x7b, 0x63, 0x58, 0x26, 0x68, 0x60, 0x13, 0xc1, 0x53, 0x4a, 0x84, 0x5b, 0x84, 0xf0, 0x52, 0x31,
	0x03, 0x45, 0xfb, 0x25, 0xa0, 0xf8, 0x95, 0x05, 0x0b, 0xb4, 0xa3, 0xf3, 0x1e, 0x02, 0x0e, 0xe1,
	0x48, 0x07, 0xd5, 0xef, 0x63, 0x80, 0x56, 0xb0, 0xf7, 0x7f, 0x12, 0xc5, 0x03, 0x00, 0xda, 0x5a,
	0x51, 0xec, 0x2e, 0xb4, 0x48, 0xd2, 0xe4, 0x72, 0x2f, 0x8a, 0x44, 0xb0, 0x9f, 0x77, 0x17, 0x5a,
	0x4f, 0x24, 0x01, 0x79, 0x15, 0xec, 0x7e, 0xc0, 0xa5, 0xb2, 0xfb, 0x01, 0xde, 0xff, 0x7e, 0x7e,
	0xf4, 0x48, 0x4e, 0xb8, 0x41, 0xb0, 0xe4, 0xfd, 0x6a, 0xc3, 0x02, 0xc1, 0xb2, 0x58, 0x61, 0xf1,
	0x8a, 0x77, 0x71, 0x12, 0xe0, 0x5e, 0x3a, 0x95, 0xba, 0x8b, 0x53, 0x1e, 0x42, 0x7b, 0x1a, 0xc7,
	0x28, 0x52, 0xb2, 0x44, 0x7a, 0x1f, 0x1b, 0x12, 0x53, 0x92, 0x25, 0xc4, 0x7a, 0x2f, 0x1f, 0x8f,
	0x27, 0xdc, 0xb4, 0x95, 0x50, 0xe5, 0x47, 0x6b, 0x9a, 0x1f, 0xd8, 0xc9, 0xe4, 0x71, 0x18, 0x71,
	0x5b, 0x58, 0x54, 0x2c, 0x36, 0x54, 0xd8, 0x89, 0x7b, 0x61, 0x3a, 0x0e, 0xd3, 0x94, 0x7d, 0x96,
	0xc8, 0xa7, 0xaa, 0xc4, 0x53, 0x3e, 0xce, 0xb3, 0x51, 0x9c, 0x84, 0xd9, 0x84, 0x18, 0xda, 0x14,
	0xa5, 0x02, 0x7b, 0xd1, 0x9e, 0x3f, 0xd6, 0xf4, 0xa4, 0x6f, 0x64, 0xf4, 0xc3, 0xf3, 0x4c, 0x46,
	0x41, 0x4a, 0xdc, 0xec, 0x08, 0x2d, 0x7a, 0x9f, 0xc3, 0xb2, 0x22, 0x77, 0xf4, 0x45, 0xec, 0x6c,
	0x72, 0x49, 0x19, 0x40, 0x75, 0xd7, 0x46, 0x76, 0xc1, 0x95, 0xbf, 0x05, 0xd0, 0x4f, 0x07, 0xf1,
	0x99, 0x5a, 0x84, 0xf7, 0xb3, 0x24, 0x0c, 0x0d, 0xa2, 0x82, 0x3e, 0x0a, 0x54, 0x90, 0x74, 0x19,
	0x2a, 0xd4, 0xf6, 0xec, 0xe7, 0x05, 0xb0, 0xa6, 0x60, 0xa2, 0x66, 0x0d, 0xc5, 0xe8, 0x41, 0x47,
	0x0d, 0x4e, 0xae, 0x90, 0x45, 0x1d, 0xbf, 0xa2, 0xc3, 0x61, 0xa4, 0x64, 0x1e, 0x26, 0xc6, 0x7c,
	0x99, 0x35, 0x78, 0x5d, 0x68, 0xf1, 0x58, 0x5a, 0x87, 0xd6, 0xc8, 0x9c, 0x5c, 0x2c, 0x79, 0xf7,
	0x0c, 0x16, 0x1b, 0x7d, 0x5d, 0x1d, 0xad, 0xfb, 0xba, 0x9e, 0x01, 0x76, 0x39, 0x77, 0xbd, 0x03,
	0xb8, 0x42, 0x0b, 0x77, 0x46, 0x7e, 0x18, 0xed, 0x87, 0x72, 0x28, 0x9d, 0x07, 0x7a, 0x72, 0x94,
	0x07, 0xb5, 0xb7, 0x6e, 0x5e, 0x48, 0x55, 0x3f, 0x1d, 0x09, 0x73, 0x81, 0xf7, 0xbd, 0xc5, 0xc1,
	0xe8, 0x1b, 0x23, 0x81, 0xe0, 0x7f, 0x19, 0xd1, 0xb8, 0x47, 0x6c, 0x03, 0x94, 0xb1, 0xd0, 0x60,
	0x6a, 0x6f, 0x79, 0x17, 0x2d, 0x2a, 0x3d, 0x85, 0xb1, 0xaa, 0xb8, 0x75, 0x75, 0x30, 0xd2, 0x45,
	0xdf, 0x3a, 0x69, 0xbc, 0x8f, 0x60, 0xd5, 0x08, 0x58, 0xc8, 0x67, 0x17, 0x96, 0x6c, 0x1d, 0x5a,
	0x8f, 0x65, 0x74, 0x9c, 0xa9, 0xa2, 0x35, 0x05, 0x4b, 0xde, 0x11, 0x2c, 0x21, 0x6b, 0xa8, 0x13,
	0x5f, 0x87, 0x25, 0xfc, 0x35, 0x1a, 0x68, 0x21, 0x6b, 0x1b, 0xfa, 0x72, 0xd9, 0x0b, 0x19, 0xa3,
	0xc4, 0x5f, 0xc5, 0x6f, 0x7a, 0x35, 0x74, 0x84, 0xa1, 0xf1, 0x7e, 0x6b, 0xc0, 0xb5, 0x9d, 0x38,
	0x4a, 0x65, 0x94, 0xe6, 0x29, 0x53, 0x20, 0xcc, 0x0e, 0xf3, 0xf1, 0xd8, 0x4f, 0x26, 0xb8, 0xb3,
	0x22, 0x7a, 0xbf, 0xa7, 0x4f, 0xd5, 0x32, 0xd2, 0x78, 0x3f, 0x91, 0xcf, 0xd5, 0x9a, 0x1e, 0x1f,
	0x6c, 0xaa, 0xaa, 0x04, 0x55, 0x0f, 0x96, 0x1a, 0x82, 0xaa, 0x67, 0x60, 0x41, 0x50, 0xea, 0x20,
	0xfd, 0x9e, 0xbb, 0x40, 0x6a, 0x2d, 0xa2, 0x45, 0x77, 0x33, 0xf5, 0x0a, 0x2c, 0x5a, 0x16, 0xce,
	0x16, 0xec, 0x1d, 0x3c, 0xda, 0xd5, 0x6c, 0xd1, 0x0a, 0xcc, 0x5f, 0x39, 0x1a, 0x8f, 0x41, 0x43,
	0x53, 0x6d, 0x55, 0xcb, 0x6a, 0x75, 0xd9, 0xaa, 0xde, 0x86, 0xd5, 0x5d, 0x99, 0x09, 0xe9, 0x07,
	0x13, 0xbe, 0x39, 0xa0, 0xc3, 0xa7, 0xb4, 0xce, 0x06, 0x5c, 0xa1, 0x23, 0xf1, 0xe5, 0xc0, 0x8e,
	0x6d, 0x72, 0x9c, 0x56, 0xcf, 0xb6, 0xb6, 0x0e, 0xf9, 0xcd, 0xb6, 0xb6, 0x41, 0x7c, 0xc6, 0x1e,
	0x2b, 0xaa, 0x72, 0x85, 0xc2, 0x6c, 0x63, 0xab, 0xaa, 0x4a, 0xba, 0x8d, 0x7d, 0x00, 0xa0, 0x1a,
	0x36, 0xb1, 0x02, 0x27, 0x42, 0xaf, 0x98, 0x21, 0x74, 0x1f, 0xfb, 0xf9, 0xd1, 0x69, 0x38, 0x2c,
	0xc7, 0x48, 0xa9, 0xf0, 0xfe, 0xb4, 0xc0, 0xad, 0x22, 0x41, 0xf8, 0x2f, 0xf4, 0xbb, 0xf6, 0xcb,
	0x4b, 0x50, 0xc2, 0x6d, 0xf2, 0x76, 0x0d, 0x7f, 0x2e, 0x5c, 0x23, 0x2e, 0x01, 0xdd, 0x1d, 0x68,
	0xf4, 0x03, 0x3d, 0xb4, 0x5e, 0xaf, 0xd9, 0xb5, 0x4c, 0x51, 0xa0, 0xa7, 0x73, 0x07, 0x9a, 0x29,
	0x62, 0xbf, 0x41, 0x71, 0xdc, 0xa8, 0x59, 0xa1, 0x69, 0x24, 0xc8, 0xd1, 0xfb, 0x10, 0xe0, 0x70,
	0xe4, 0x27, 0x52, 0x11, 0x19, 0xff, 0x91, 0xc8, 0xe1, 0x89, 0x9c, 0x70, 0xa9, 0x58, 0xe2, 0x59,
	0x78, 0x52, 0x19, 0xb9, 0x27, 0x72, 0xe2, 0xfd, 0x61, 0xc1, 0xf5, 0x22, 0xfa, 0x72, 0x1f, 0x5d,
	0x2a, 0x7c, 0x36, 0xf6, 0x0f, 0x0d, 0xa2, 0x6a, 0xd1, 0x44, 0xb7, 0x5d, 0x45, 0x37, 0xfe, 0xa9,
	0x92, 0x69, 0xc6, 0xfc, 0xa4, 0x6f, 0xe7, 0xbe, 0x19, 0x24, 0xb1, 0xa4, 0xbe, 0x1a, 0xa5, 0x93,
	0x30, 0xb3, 0xba, 0x03, 0x4d, 0x6a, 0x08, 0x0b, 0x73, 0x14, 0x05, 0xbf, 0xbc, 0x9f, 0x2b, 0x69,
	0x85, 0xc7, 0x91, 0x2a, 0xf3, 0xbf, 0x49, 0x0b, 0x2b, 0x8b, 0x1b, 0x3d, 0xe2, 0xc4, 0x58, 0x72,
	0xee, 0x95, 0x8d, 0x8d, 0x13, 0xbb, 0x34, 0xbe, 0xb2, 0x0b, 0xaa, 0x20, 0x8a, 0xbc, 0x54, 0x10,
	0x14, 0xfd, 0xd7, 0x16, 0x38, 0xf8, 0xaa, 0x0d, 0x87, 0x6a, 0xd4, 0x32, 0x96, 0x8a, 0x37, 0x7c,
	0xaf, 0x88, 0x9a, 0x9b, 0x93, 0xb6, 0xec, 0x3f, 0xd2, 0x51, 0xb3, 0xe8, 0x3c, 0x80, 0xc6, 0x6e,
	0x98, 0x32, 0x9a, 0xfe, 0x19, 0xaa, 0x71, 0xa1, 0xf7, 0x83, 0x05, 0x37, 0x66, 0x5d, 0x64, 0xa0,
	0x2b, 0xf9, 0x59, 0x5d, 0xa4, 0x4c, 0xa2, 0xb7, 0xea, 0xea, 0x30, 0xe3, 0x2c, 0xea, 0x52, 0xd5,
	0x17, 0x6e, 0xcf, 0x7b, 0xe1, 0x3f, 0x59, 0xf0, 0x5a, 0x11, 0x27, 0xbf, 0x04, 0xcc, 0xdb, 0x2e,
	0xea, 0x66, 0x4d, 0xd5, 0x4d, 0xff, 0x6f, 0xe3, 0xba, 0xd5, 0xfc, 0x6f, 0x6b, 0x14, 0x16, 0xfd,
	0xbf, 0xcd, 0xfc, 0xef, 0xda, 0x9c, 0xfd, 0xef, 0xaa, 0x83, 0x6f, 0xcd, 0x1b, 0xfc, 0xb7, 0x96,
	0xd1, 0x91, 0x68, 0x27, 0x0e, 0x7d, 0xdb, 0x4f, 0xa5, 0xb3, 0x09, 0xf6, 0xf6, 0x68, 0xce, 0xf7,
	0xbf, 0xbd, 0x3d, 0x32, 0xd3, 0xb5, 0xab, 0xe9, 0xea, 0xc0, 0x1a, 0xf3, 0x06, 0xb6, 0x0b, 0xff,
	0xaf, 0x8d, 0xcb, 0x7c, 0xa3, 0xd8, 0x73, 0xbc, 0x51, 0xbc, 0xdf, 0x2d, 0xb8, 0x55, 0x5e, 0x4f,
	0x22, 0xfd, 0x4c, 0xbe, 0xca, 0xae, 0xbc, 0x56, 0x76, 0xe5, 0xce, 0x4b, 0xb6, 0xdd, 0x5f, 0x2c,
	0x78, 0xa3, 0x2e, 0x23, 0xf5, 0x1c, 0x79, 0x15, 0x83, 0x46, 0x25, 0x60, 0xcf, 0x99, 0xc0, 0x5f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x11, 0x5e, 0x8c, 0xdb, 0x7b, 0x13, 0x00, 0x00,
}
